import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'es' | 'en' | 'pt' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Quiénes Somos',
    'nav.specialties': 'Especialidades',
    'nav.services': 'Servicios',
    'nav.appointments': 'Reservar',
    'nav.locations': 'Sucursales',
    'nav.contact': 'Contacto',
    'nav.login': 'Iniciar Sesión',
    'nav.portal': 'Mi Portal',
    'nav.bookNow': 'Agendar Cita',
    
    // Hero
    'hero.badge': '✨ Desde 1985 cuidando tu salud',
    'hero.title1': 'Tradición, Calidad y',
    'hero.title2': 'Bienestar Natural',
    'hero.specialistsIn': 'Especialistas en',
    'hero.service1': 'Jarabes Naturales',
    'hero.service2': 'Pomadas Medicinales',
    'hero.service3': 'Aceites Esenciales',
    'hero.service4': 'Productos de Rebotica',
    'hero.cta': 'Comprar Ahora',
    'hero.secondary': 'Conocer Más',
    'hero.years': 'Años',
    'hero.branches': 'Categorías',
    'hero.specialties': 'Productos',
    'hero.patients': 'Clientes',
    
    // About
    'about.badge': 'Quiénes Somos',
    'about.title1': 'Vanguardia en',
    'about.title2': 'Odontología Digital',
    'about.description': 'En <strong>NovellDent</strong> nos enfocamos en brindarte la mejor experiencia en salud dental, con tecnología de punta y un equipo de especialistas comprometidos con tu bienestar.',
    'about.yearsExperience': 'Años de experiencia',
    'about.feature1.title': 'Tecnología Digital',
    'about.feature1.desc': 'Equipos de última generación para diagnósticos precisos.',
    'about.feature2.title': 'Seguridad Total',
    'about.feature2.desc': 'Protocolos rigurosos de higiene y bioseguridad.',
    'about.feature3.title': 'Certificados',
    'about.feature3.desc': 'Especialistas con amplia experiencia y constante actualización.',
    'about.feature4.title': 'Personalizado',
    'about.feature4.desc': 'Tratamientos diseñados específicamente para ti.',
    
    // Services
    'services.badge': 'Servicios',
    'services.title': 'Resultados que transforman',
    'services.subtitle': 'Tratamientos con planificación precisa para alcanzar resultados óptimos.',
    'services.whitening': 'Blanqueamiento',
    'services.whitening.desc': 'Recupera el blanco natural de tus dientes con tecnología LED profesional.',
    'services.whitening.f1': 'Resultados inmediatos',
    'services.whitening.f2': 'Sin sensibilidad',
    'services.implants': 'Implantes',
    'services.implants.desc': 'Reemplaza piezas dentales con implantes de titanio de alta calidad.',
    'services.implants.f1': 'Biocompatibles',
    'services.implants.f2': 'Duraderos',
    'services.orthodontics': 'Ortodoncia',
    'services.orthodontics.desc': 'Alineadores transparentes para corregir tu sonrisa discretamente.',
    'services.orthodontics.f1': 'Casi invisibles',
    'services.orthodontics.f2': 'Removibles',
    'services.smileDesign': 'Diseño de Sonrisa',
    'services.smileDesign.desc': 'Transformación completa con carillas y técnicas de estética dental.',
    'services.smileDesign.f1': 'Personalizado',
    'services.smileDesign.f2': 'Resultados naturales',
    'services.schedule': 'Agendar',
    
    // Specialties
    'specialties.badge': 'Especialidades',
    'specialties.title': 'Expertos en cada área',
    'specialties.subtitle': 'Un equipo multidisciplinario para un diagnóstico completo y preciso.',
    'specialties.general': 'Odontología General',
    'specialties.endodontics': 'Endodoncia',
    'specialties.implantology': 'Implantología',
    'specialties.maxillofacial': 'Estética Maxilofacial',
    'specialties.orthodontics': 'Ortodoncia',
    'specialties.pediatric': 'Odontología Pediátrica',
    'specialties.prosthetics': 'Prótesis Dental',
    'specialties.surgery': 'Cirugía Oral',
    'specialties.aesthetics': 'Estética Dental',
    
    // Testimonials
    'testimonials.badge': 'Testimonios',
    'testimonials.title': 'Lo que dicen',
    'testimonials.titleHighlight': 'nuestros pacientes',
    'testimonials.subtitle': 'Historias reales de personas que transformaron su sonrisa con nosotros.',
    'testimonials.patientSince': 'Paciente desde',
    
    // Reviews
    'reviews.badge': 'Opiniones de Pacientes',
    'reviews.title': 'Lo que dicen',
    'reviews.titleHighlight': 'nuestros pacientes',
    'reviews.reviews': 'reseñas',
    
    // CTA
    'cta.title': 'Tu nueva sonrisa te espera',
    'cta.subtitle': 'Agenda tu cita de valoración sin costo y descubre cómo podemos transformar tu sonrisa con la mejor tecnología dental.',
    'cta.button': 'Agendar Cita Gratis',
    'cta.call': 'Llamar Ahora',
    
    // Appointments
    'appointments.badge': 'Reserva Online',
    'appointments.title': 'Agenda tu',
    'appointments.titleHighlight': 'cita ahora',
    'appointments.subtitle': 'Reserva tu cita en línea de forma rápida y sencilla. Selecciona tu sucursal, fecha y hora preferida.',
    'appointments.step.branch': 'Sucursal',
    'appointments.step.date': 'Fecha',
    'appointments.step.time': 'Hora',
    'appointments.step.data': 'Datos',
    'appointments.selectBranch': 'Selecciona una Sucursal',
    'appointments.serviceType': 'Tipo de Servicio',
    'appointments.selectService': 'Selecciona un servicio',
    'appointments.selectDate': 'Selecciona una Fecha',
    'appointments.selectTime': 'Selecciona una Hora Disponible',
    'appointments.loadingSlots': 'Cargando horarios...',
    'appointments.noSlots': 'No hay horarios disponibles para esta fecha y sucursal.',
    'appointments.selectAnotherDate': 'Seleccionar otra fecha',
    'appointments.morning': 'Mañana',
    'appointments.afternoon': 'Tarde',
    'appointments.yourData': 'Tus Datos',
    'appointments.summary': 'Resumen de tu cita',
    'appointments.fullName': 'Nombre completo',
    'appointments.fullNamePlaceholder': 'Tu nombre completo',
    'appointments.phone': 'Teléfono',
    'appointments.phonePlaceholder': 'Tu número de teléfono',
    'appointments.email': 'Correo electrónico',
    'appointments.emailPlaceholder': 'tu@email.com',
    'appointments.referralCode': 'Código de Referido',
    'appointments.referralPlaceholder': 'REF-XXXXXXXX',
    'appointments.referralOptional': '(opcional)',
    'appointments.referralHint': '¿Tienes un código de referido? Obtén 5% de descuento',
    'appointments.validCode': '¡Código válido! Obtendrás 5% de descuento',
    'appointments.invalidCode': 'Código no válido',
    'appointments.available': 'Disponible',
    'appointments.selected': 'Seleccionado',
    'appointments.booked': 'Ocupado',
    'appointments.back': 'Atrás',
    'appointments.continue': 'Continuar',
    'appointments.confirm': 'Confirmar Cita',
    'appointments.confirming': 'Confirmando...',
    'appointments.confirmed': '¡Cita Confirmada!',
    'appointments.confirmationEmail': 'Te hemos enviado un correo de confirmación a',
    'appointments.bookAnother': 'Agendar otra cita',
    'appointments.discountApplied': 'Te hemos enviado un correo. ¡Tienes 5% de descuento por código de referido!',
    'appointments.hrs': 'hrs',
    
    // Confirmation Screen
    'confirmation.title': '¡Reserva Completada!',
    'confirmation.subtitle': 'Tu cita ha sido agendada exitosamente',
    'confirmation.emailSent': 'Te hemos enviado un correo de confirmación a',
    'confirmation.createAccount': 'Crea tu cuenta de paciente',
    'confirmation.createAccountDesc': 'Accede a tu historial, próximas citas y más',
    'confirmation.password': 'Crea una contraseña',
    'confirmation.passwordPlaceholder': 'Mínimo 6 caracteres',
    'confirmation.register': 'Crear mi cuenta',
    'confirmation.registering': 'Creando cuenta...',
    'confirmation.skipForNow': 'Omitir por ahora',
    'confirmation.accountCreated': '¡Cuenta creada exitosamente!',
    'confirmation.accountCreatedDesc': 'Ahora puedes acceder a tu portal de paciente',
    'confirmation.goToPortal': 'Ir a Mi Portal',
    
    // Locations
    'locations.badge': 'Sucursales',
    'locations.title': 'Encuentra tu',
    'locations.titleHighlight': 'clínica más cercana',
    'locations.subtitle': 'Con 5 ubicaciones estratégicas en Nayarit y Jalisco, siempre hay una clínica NovellDent cerca de ti.',
    'locations.viewMap': 'Ver mapa completo',
    'locations.hours': 'Lun - Sáb: 9:00 - 19:00',
    'locations.directions': 'Cómo llegar',
    
    // Contact
    'contact.badge': 'Contacto',
    'contact.title': '¿Listo para',
    'contact.titleHighlight': 'transformar tu sonrisa',
    'contact.subtitle': 'Estamos aquí para responder todas tus preguntas. Contáctanos y agenda tu cita hoy mismo.',
    'contact.callUs': 'Llámanos',
    'contact.whatsapp': 'WhatsApp',
    'contact.email': 'Email',
    'contact.formTitle': 'Agenda tu Cita',
    'contact.name': 'Nombre',
    'contact.namePlaceholder': 'Tu nombre',
    'contact.phonePlaceholder': 'Tu teléfono',
    'contact.emailPlaceholder': 'tu@email.com',
    'contact.service': 'Servicio de interés',
    'contact.servicePlaceholder': 'Ej: Blanqueamiento dental',
    'contact.message': 'Mensaje',
    'contact.messagePlaceholder': 'Cuéntanos sobre tu caso...',
    'contact.send': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
    'contact.sent': '¡Mensaje enviado!',
    'contact.sentDesc': 'Nos pondremos en contacto contigo pronto.',
    
    // Footer
    'footer.description': 'NovellDent Digital Dentistry. Tecnología de vanguardia para tu sonrisa perfecta.',
    'footer.services': 'Servicios',
    'footer.generalDentistry': 'Odontología General',
    'footer.whitening': 'Blanqueamiento',
    'footer.implants': 'Implantes',
    'footer.orthodontics': 'Ortodoncia',
    'footer.aesthetics': 'Estética Dental',
    'footer.specialties': 'Especialidades',
    'footer.endodontics': 'Endodoncia',
    'footer.periodontics': 'Periodoncia',
    'footer.oralSurgery': 'Cirugía Oral',
    'footer.pediatric': 'Odontopediatría',
    'footer.prosthetics': 'Prótesis',
    'footer.contact': 'Contacto',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.privacy': 'Aviso de Privacidad',
    'footer.terms': 'Términos y Condiciones',
    
    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.fullName': 'Nombre completo',
    'auth.phone': 'Teléfono',
    'auth.continue': 'Continuar',
    'auth.createAccount': 'Crear cuenta',
    'auth.welcome': 'Bienvenido',
    'auth.accessPortal': 'Accede a tu portal dental',
    'auth.joinUs': 'Únete a NovellDent',
    'auth.patient': 'Paciente',
    'auth.doctor': 'Doctor',
    'auth.experience': 'Experiencia dental de primer nivel',
    
    // ChatBot
    'chatbot.title': 'Denti',
    'chatbot.subtitle': 'Tu asistente dental 🦷',
    'chatbot.greeting': '¡Hola! 👋',
    'chatbot.greetingText': 'Soy Denti, tu asistente virtual. ¿En qué puedo ayudarte?',
    'chatbot.placeholder': 'Escribe tu mensaje...',
    'chatbot.typing': 'Escribiendo...',
    'chatbot.services': 'Servicios',
    'chatbot.branches': 'Sucursales',
    'chatbot.appointment': 'Cita',
    'chatbot.prices': 'Precios',
    'chatbot.servicesQ': '¿Qué servicios ofrecen?',
    'chatbot.branchesQ': '¿Cuáles son sus sucursales y horarios?',
    'chatbot.appointmentQ': '¿Cómo puedo agendar una cita?',
    'chatbot.pricesQ': '¿Cuáles son sus precios?',
    
    // Dashboard Common
    'dashboard.appointments': 'Citas',
    'dashboard.calendar': 'Calendario',
    'dashboard.doctors': 'Doctores',
    'dashboard.analytics': 'Analytics',
    'dashboard.metrics': 'Métricas',
    'dashboard.reviews': 'Reseñas',
    'dashboard.files': 'Archivos',
    'dashboard.prescriptions': 'Recetas',
    'dashboard.documents': 'Documentos',
    'dashboard.referrals': 'Referidos',
    'dashboard.xrayAI': 'RX IA',
    'dashboard.aiReports': 'Reportes IA',
    'dashboard.simulator': 'Simulador',
    'dashboard.contactCenter': 'Contact Center',
    'dashboard.internalChat': 'Chat Interno',
    'dashboard.logout': 'Cerrar Sesión',
    'dashboard.total': 'Total Citas',
    'dashboard.pending': 'Pendientes',
    'dashboard.confirmed': 'Confirmadas',
    'dashboard.today': 'Hoy',
    'dashboard.tomorrow': 'Mañana',
    'dashboard.noAppointments': 'No hay citas',
    'dashboard.noAppointmentsFiltered': 'No se encontraron citas con los filtros seleccionados.',
    'dashboard.noAppointmentsYet': 'Aún no hay citas agendadas.',
    'dashboard.loading': 'Cargando citas...',
    'dashboard.searchPlaceholder': 'Buscar por nombre, email o teléfono...',
    'dashboard.all': 'Todos',
    'dashboard.allLocations': 'Todas',
    'dashboard.status': 'Estado',
    'dashboard.branch': 'Sucursal',
    
    // Admin Dashboard
    'admin.title': 'Panel de Administración',
    'admin.completed': 'Completadas',
    'admin.cancelled': 'Canceladas',
    
    // Doctor Dashboard
    'doctor.title': 'Portal del Doctor',
    'doctor.todayAppointments': 'Citas Hoy',
    'doctor.activeTreatments': 'Tratamientos Activos',
    'doctor.thisWeek': 'Esta Semana',
    'doctor.weeklyCalendar': 'Calendario Semanal',
    'doctor.appointmentsOf': 'Citas del',
    'doctor.noAppointmentsDay': 'No hay citas para este día',
    'doctor.patients': 'Pacientes',
    'doctor.treatments': 'Tratamientos',
    'doctor.complete': 'Completar',
    
    // Common
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.print': 'Imprimir',
    
    // Brands Section
    'brands.title': 'Marcas que Usamos',
    'brands.subtitle': 'Trabajamos con las mejores marcas del mundo en tecnología dental',
    
    // Technology Section
    'technology.title': 'Contamos con la Mejor Tecnología',
    'technology.subtitle': 'Utilizamos equipos y software de vanguardia para ofrecerte los mejores resultados',
    'technology.precision': 'Precisión Digital',
    'technology.precisionDesc': 'Escaneo 3D intraoral para restauraciones exactas',
    'technology.speed': 'Rapidez',
    'technology.speedDesc': 'Diseño y fabricación en el mismo día',
    'technology.quality': 'Calidad Superior',
    'technology.qualityDesc': 'Materiales de última generación certificados',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.specialties': 'Specialties',
    'nav.services': 'Services',
    'nav.appointments': 'Book',
    'nav.locations': 'Locations',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.portal': 'My Portal',
    'nav.bookNow': 'Book Appointment',
    
    // Hero
    'hero.badge': 'Cutting-Edge Digital Dentistry',
    'hero.title1': 'Your smile.',
    'hero.title2': 'Perfected.',
    'hero.specialistsIn': 'Specialists in',
    'hero.service1': 'Dental Implants',
    'hero.service2': 'Invisible Orthodontics',
    'hero.service3': 'Whitening',
    'hero.service4': 'Smile Design',
    'hero.cta': 'Book Appointment',
    'hero.secondary': 'Learn More',
    'hero.years': 'Years',
    'hero.branches': 'Branches',
    'hero.specialties': 'Specialties',
    'hero.patients': 'Patients',
    
    // About
    'about.badge': 'About Us',
    'about.title1': 'Excellence in',
    'about.title2': 'Digital Dentistry',
    'about.description': 'At <strong>NovellDent</strong> we focus on providing you the best dental health experience, with cutting-edge technology and a team of specialists committed to your well-being.',
    'about.yearsExperience': 'Years of experience',
    'about.feature1.title': 'Digital Technology',
    'about.feature1.desc': 'State-of-the-art equipment for accurate diagnostics.',
    'about.feature2.title': 'Total Safety',
    'about.feature2.desc': 'Rigorous hygiene and biosafety protocols.',
    'about.feature3.title': 'Certified',
    'about.feature3.desc': 'Specialists with extensive experience and constant updates.',
    'about.feature4.title': 'Personalized',
    'about.feature4.desc': 'Treatments designed specifically for you.',
    
    // Services
    'services.badge': 'Services',
    'services.title': 'Transforming results',
    'services.subtitle': 'Treatments with precise planning to achieve optimal results.',
    'services.whitening': 'Whitening',
    'services.whitening.desc': 'Restore the natural white of your teeth with professional LED technology.',
    'services.whitening.f1': 'Immediate results',
    'services.whitening.f2': 'No sensitivity',
    'services.implants': 'Implants',
    'services.implants.desc': 'Replace dental pieces with high-quality titanium implants.',
    'services.implants.f1': 'Biocompatible',
    'services.implants.f2': 'Long-lasting',
    'services.orthodontics': 'Orthodontics',
    'services.orthodontics.desc': 'Transparent aligners to correct your smile discreetly.',
    'services.orthodontics.f1': 'Almost invisible',
    'services.orthodontics.f2': 'Removable',
    'services.smileDesign': 'Smile Design',
    'services.smileDesign.desc': 'Complete transformation with veneers and dental aesthetic techniques.',
    'services.smileDesign.f1': 'Personalized',
    'services.smileDesign.f2': 'Natural results',
    'services.schedule': 'Schedule',
    
    // Specialties
    'specialties.badge': 'Specialties',
    'specialties.title': 'Experts in every area',
    'specialties.subtitle': 'A multidisciplinary team for complete and accurate diagnosis.',
    'specialties.general': 'General Dentistry',
    'specialties.endodontics': 'Endodontics',
    'specialties.implantology': 'Implantology',
    'specialties.maxillofacial': 'Maxillofacial Aesthetics',
    'specialties.orthodontics': 'Orthodontics',
    'specialties.pediatric': 'Pediatric Dentistry',
    'specialties.prosthetics': 'Dental Prosthetics',
    'specialties.surgery': 'Oral Surgery',
    'specialties.aesthetics': 'Dental Aesthetics',
    
    // Testimonials
    'testimonials.badge': 'Testimonials',
    'testimonials.title': 'What',
    'testimonials.titleHighlight': 'our patients say',
    'testimonials.subtitle': 'Real stories from people who transformed their smile with us.',
    'testimonials.patientSince': 'Patient since',
    
    // Reviews
    'reviews.badge': 'Patient Reviews',
    'reviews.title': 'What',
    'reviews.titleHighlight': 'our patients say',
    'reviews.reviews': 'reviews',
    
    // CTA
    'cta.title': 'Your new smile awaits',
    'cta.subtitle': 'Book your free consultation and discover how we can transform your smile with the best dental technology.',
    'cta.button': 'Book Free Appointment',
    'cta.call': 'Call Now',
    
    // Appointments
    'appointments.badge': 'Online Booking',
    'appointments.title': 'Book your',
    'appointments.titleHighlight': 'appointment now',
    'appointments.subtitle': 'Book your appointment online quickly and easily. Select your preferred branch, date and time.',
    'appointments.step.branch': 'Branch',
    'appointments.step.date': 'Date',
    'appointments.step.time': 'Time',
    'appointments.step.data': 'Details',
    'appointments.selectBranch': 'Select a Branch',
    'appointments.serviceType': 'Type of Service',
    'appointments.selectService': 'Select a service',
    'appointments.selectDate': 'Select a Date',
    'appointments.selectTime': 'Select an Available Time',
    'appointments.loadingSlots': 'Loading schedules...',
    'appointments.noSlots': 'No times available for this date and branch.',
    'appointments.selectAnotherDate': 'Select another date',
    'appointments.morning': 'Morning',
    'appointments.afternoon': 'Afternoon',
    'appointments.yourData': 'Your Details',
    'appointments.summary': 'Appointment summary',
    'appointments.fullName': 'Full name',
    'appointments.fullNamePlaceholder': 'Your full name',
    'appointments.phone': 'Phone',
    'appointments.phonePlaceholder': 'Your phone number',
    'appointments.email': 'Email',
    'appointments.emailPlaceholder': 'you@email.com',
    'appointments.referralCode': 'Referral Code',
    'appointments.referralPlaceholder': 'REF-XXXXXXXX',
    'appointments.referralOptional': '(optional)',
    'appointments.referralHint': 'Have a referral code? Get 5% discount',
    'appointments.validCode': 'Valid code! You will get 5% discount',
    'appointments.invalidCode': 'Invalid code',
    'appointments.available': 'Available',
    'appointments.selected': 'Selected',
    'appointments.booked': 'Booked',
    'appointments.back': 'Back',
    'appointments.continue': 'Continue',
    'appointments.confirm': 'Confirm Appointment',
    'appointments.confirming': 'Confirming...',
    'appointments.confirmed': 'Appointment Confirmed!',
    'appointments.confirmationEmail': 'We have sent a confirmation email to',
    'appointments.bookAnother': 'Book another appointment',
    'appointments.discountApplied': 'We have sent you an email. You have a 5% discount with your referral code!',
    'appointments.hrs': 'hrs',
    
    // Confirmation Screen
    'confirmation.title': 'Booking Complete!',
    'confirmation.subtitle': 'Your appointment has been successfully scheduled',
    'confirmation.emailSent': 'We have sent a confirmation email to',
    'confirmation.createAccount': 'Create your patient account',
    'confirmation.createAccountDesc': 'Access your history, upcoming appointments and more',
    'confirmation.password': 'Create a password',
    'confirmation.passwordPlaceholder': 'Minimum 6 characters',
    'confirmation.register': 'Create my account',
    'confirmation.registering': 'Creating account...',
    'confirmation.skipForNow': 'Skip for now',
    'confirmation.accountCreated': 'Account created successfully!',
    'confirmation.accountCreatedDesc': 'You can now access your patient portal',
    'confirmation.goToPortal': 'Go to My Portal',
    
    // Locations
    'locations.badge': 'Locations',
    'locations.title': 'Find your',
    'locations.titleHighlight': 'nearest clinic',
    'locations.subtitle': 'With 5 strategic locations in Nayarit and Jalisco, there is always a NovellDent clinic near you.',
    'locations.viewMap': 'View full map',
    'locations.hours': 'Mon - Sat: 9:00 AM - 7:00 PM',
    'locations.directions': 'Get directions',
    
    // Contact
    'contact.badge': 'Contact',
    'contact.title': 'Ready to',
    'contact.titleHighlight': 'transform your smile',
    'contact.subtitle': 'We are here to answer all your questions. Contact us and book your appointment today.',
    'contact.callUs': 'Call us',
    'contact.whatsapp': 'WhatsApp',
    'contact.email': 'Email',
    'contact.formTitle': 'Book Your Appointment',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Your name',
    'contact.phonePlaceholder': 'Your phone',
    'contact.emailPlaceholder': 'you@email.com',
    'contact.service': 'Service of interest',
    'contact.servicePlaceholder': 'E.g: Teeth whitening',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us about your case...',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.sent': 'Message sent!',
    'contact.sentDesc': 'We will contact you soon.',
    
    // Footer
    'footer.description': 'NovellDent Digital Dentistry. Cutting-edge technology for your perfect smile.',
    'footer.services': 'Services',
    'footer.generalDentistry': 'General Dentistry',
    'footer.whitening': 'Whitening',
    'footer.implants': 'Implants',
    'footer.orthodontics': 'Orthodontics',
    'footer.aesthetics': 'Dental Aesthetics',
    'footer.specialties': 'Specialties',
    'footer.endodontics': 'Endodontics',
    'footer.periodontics': 'Periodontics',
    'footer.oralSurgery': 'Oral Surgery',
    'footer.pediatric': 'Pediatric Dentistry',
    'footer.prosthetics': 'Prosthetics',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms and Conditions',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full name',
    'auth.phone': 'Phone',
    'auth.continue': 'Continue',
    'auth.createAccount': 'Create account',
    'auth.welcome': 'Welcome',
    'auth.accessPortal': 'Access your dental portal',
    'auth.joinUs': 'Join NovellDent',
    'auth.patient': 'Patient',
    'auth.doctor': 'Doctor',
    'auth.experience': 'First-class dental experience',
    
    // ChatBot
    'chatbot.title': 'Denti',
    'chatbot.subtitle': 'Your dental assistant 🦷',
    'chatbot.greeting': 'Hello! 👋',
    'chatbot.greetingText': "I'm Denti, your virtual assistant. How can I help you?",
    'chatbot.placeholder': 'Type your message...',
    'chatbot.typing': 'Typing...',
    'chatbot.services': 'Services',
    'chatbot.branches': 'Locations',
    'chatbot.appointment': 'Appointment',
    'chatbot.prices': 'Prices',
    'chatbot.servicesQ': 'What services do you offer?',
    'chatbot.branchesQ': 'What are your locations and hours?',
    'chatbot.appointmentQ': 'How can I book an appointment?',
    'chatbot.pricesQ': 'What are your prices?',
    
    // Dashboard Common
    'dashboard.appointments': 'Appointments',
    'dashboard.calendar': 'Calendar',
    'dashboard.doctors': 'Doctors',
    'dashboard.analytics': 'Analytics',
    'dashboard.metrics': 'Metrics',
    'dashboard.reviews': 'Reviews',
    'dashboard.files': 'Files',
    'dashboard.prescriptions': 'Prescriptions',
    'dashboard.documents': 'Documents',
    'dashboard.referrals': 'Referrals',
    'dashboard.xrayAI': 'X-Ray AI',
    'dashboard.aiReports': 'AI Reports',
    'dashboard.simulator': 'Simulator',
    'dashboard.contactCenter': 'Contact Center',
    'dashboard.internalChat': 'Internal Chat',
    'dashboard.logout': 'Log Out',
    'dashboard.total': 'Total Appointments',
    'dashboard.pending': 'Pending',
    'dashboard.confirmed': 'Confirmed',
    'dashboard.today': 'Today',
    'dashboard.tomorrow': 'Tomorrow',
    'dashboard.noAppointments': 'No appointments',
    'dashboard.noAppointmentsFiltered': 'No appointments found with selected filters.',
    'dashboard.noAppointmentsYet': 'No appointments scheduled yet.',
    'dashboard.loading': 'Loading appointments...',
    'dashboard.searchPlaceholder': 'Search by name, email or phone...',
    'dashboard.all': 'All',
    'dashboard.allLocations': 'All',
    'dashboard.status': 'Status',
    'dashboard.branch': 'Branch',
    
    // Admin Dashboard
    'admin.title': 'Admin Panel',
    'admin.completed': 'Completed',
    'admin.cancelled': 'Cancelled',
    
    // Doctor Dashboard
    'doctor.title': 'Doctor Portal',
    'doctor.todayAppointments': 'Appointments Today',
    'doctor.activeTreatments': 'Active Treatments',
    'doctor.thisWeek': 'This Week',
    'doctor.weeklyCalendar': 'Weekly Calendar',
    'doctor.appointmentsOf': 'Appointments of',
    'doctor.noAppointmentsDay': 'No appointments for this day',
    'doctor.patients': 'Patients',
    'doctor.treatments': 'Treatments',
    'doctor.complete': 'Complete',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.print': 'Print',
    
    // Brands Section
    'brands.title': 'Brands We Use',
    'brands.subtitle': 'We work with the best dental technology brands in the world',
    
    // Technology Section
    'technology.title': 'Best-in-Class Technology',
    'technology.subtitle': 'We use cutting-edge equipment and software to deliver the best results',
    'technology.precision': 'Digital Precision',
    'technology.precisionDesc': 'Intraoral 3D scanning for exact restorations',
    'technology.speed': 'Speed',
    'technology.speedDesc': 'Same-day design and manufacturing',
    'technology.quality': 'Superior Quality',
    'technology.qualityDesc': 'Certified next-generation materials',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.about': 'Sobre Nós',
    'nav.specialties': 'Especialidades',
    'nav.services': 'Serviços',
    'nav.appointments': 'Agendar',
    'nav.locations': 'Unidades',
    'nav.contact': 'Contato',
    'nav.login': 'Entrar',
    'nav.portal': 'Meu Portal',
    'nav.bookNow': 'Agendar Consulta',
    
    // Hero
    'hero.badge': 'Odontologia Digital de Ponta',
    'hero.title1': 'Seu sorriso.',
    'hero.title2': 'Aperfeiçoado.',
    'hero.specialistsIn': 'Especialistas em',
    'hero.service1': 'Implantes Dentários',
    'hero.service2': 'Ortodontia Invisível',
    'hero.service3': 'Clareamento',
    'hero.service4': 'Design de Sorriso',
    'hero.cta': 'Agendar Consulta',
    'hero.secondary': 'Saiba Mais',
    'hero.years': 'Anos',
    'hero.branches': 'Unidades',
    'hero.specialties': 'Especialidades',
    'hero.patients': 'Pacientes',
    
    // About
    'about.badge': 'Sobre Nós',
    'about.title1': 'Excelência em',
    'about.title2': 'Odontologia Digital',
    'about.description': 'Na <strong>NovellDent</strong> nos concentramos em oferecer a melhor experiência em saúde dental, com tecnologia de ponta e uma equipe de especialistas comprometidos com seu bem-estar.',
    'about.yearsExperience': 'Anos de experiência',
    'about.feature1.title': 'Tecnologia Digital',
    'about.feature1.desc': 'Equipamentos de última geração para diagnósticos precisos.',
    'about.feature2.title': 'Segurança Total',
    'about.feature2.desc': 'Protocolos rigorosos de higiene e biossegurança.',
    'about.feature3.title': 'Certificados',
    'about.feature3.desc': 'Especialistas com ampla experiência e atualização constante.',
    'about.feature4.title': 'Personalizado',
    'about.feature4.desc': 'Tratamentos projetados especificamente para você.',
    
    // Services
    'services.badge': 'Serviços',
    'services.title': 'Resultados que transformam',
    'services.subtitle': 'Tratamentos com planejamento preciso para alcançar resultados ótimos.',
    'services.whitening': 'Clareamento',
    'services.whitening.desc': 'Recupere o branco natural dos seus dentes com tecnologia LED profissional.',
    'services.whitening.f1': 'Resultados imediatos',
    'services.whitening.f2': 'Sem sensibilidade',
    'services.implants': 'Implantes',
    'services.implants.desc': 'Substitua peças dentárias com implantes de titânio de alta qualidade.',
    'services.implants.f1': 'Biocompatíveis',
    'services.implants.f2': 'Duráveis',
    'services.orthodontics': 'Ortodontia',
    'services.orthodontics.desc': 'Alinhadores transparentes para corrigir seu sorriso discretamente.',
    'services.orthodontics.f1': 'Quase invisíveis',
    'services.orthodontics.f2': 'Removíveis',
    'services.smileDesign': 'Design de Sorriso',
    'services.smileDesign.desc': 'Transformação completa com lentes e técnicas de estética dental.',
    'services.smileDesign.f1': 'Personalizado',
    'services.smileDesign.f2': 'Resultados naturais',
    'services.schedule': 'Agendar',
    
    // Specialties
    'specialties.badge': 'Especialidades',
    'specialties.title': 'Especialistas em cada área',
    'specialties.subtitle': 'Uma equipe multidisciplinar para diagnóstico completo e preciso.',
    'specialties.general': 'Odontologia Geral',
    'specialties.endodontics': 'Endodontia',
    'specialties.implantology': 'Implantodontia',
    'specialties.maxillofacial': 'Estética Maxilofacial',
    'specialties.orthodontics': 'Ortodontia',
    'specialties.pediatric': 'Odontopediatria',
    'specialties.prosthetics': 'Prótese Dentária',
    'specialties.surgery': 'Cirurgia Oral',
    'specialties.aesthetics': 'Estética Dental',
    
    // Testimonials
    'testimonials.badge': 'Depoimentos',
    'testimonials.title': 'O que dizem',
    'testimonials.titleHighlight': 'nossos pacientes',
    'testimonials.subtitle': 'Histórias reais de pessoas que transformaram seu sorriso conosco.',
    'testimonials.patientSince': 'Paciente desde',
    
    // Reviews
    'reviews.badge': 'Avaliações de Pacientes',
    'reviews.title': 'O que dizem',
    'reviews.titleHighlight': 'nossos pacientes',
    'reviews.reviews': 'avaliações',
    
    // CTA
    'cta.title': 'Seu novo sorriso espera por você',
    'cta.subtitle': 'Agende sua consulta de avaliação gratuita e descubra como podemos transformar seu sorriso com a melhor tecnologia dental.',
    'cta.button': 'Agendar Consulta Grátis',
    'cta.call': 'Ligar Agora',
    
    // Appointments
    'appointments.badge': 'Reserva Online',
    'appointments.title': 'Agende sua',
    'appointments.titleHighlight': 'consulta agora',
    'appointments.subtitle': 'Agende sua consulta online de forma rápida e fácil. Selecione sua unidade, data e horário preferidos.',
    'appointments.step.branch': 'Unidade',
    'appointments.step.date': 'Data',
    'appointments.step.time': 'Hora',
    'appointments.step.data': 'Dados',
    'appointments.selectBranch': 'Selecione uma Unidade',
    'appointments.serviceType': 'Tipo de Serviço',
    'appointments.selectService': 'Selecione um serviço',
    'appointments.selectDate': 'Selecione uma Data',
    'appointments.selectTime': 'Selecione um Horário Disponível',
    'appointments.loadingSlots': 'Carregando horários...',
    'appointments.noSlots': 'Não há horários disponíveis para esta data e unidade.',
    'appointments.selectAnotherDate': 'Selecionar outra data',
    'appointments.morning': 'Manhã',
    'appointments.afternoon': 'Tarde',
    'appointments.yourData': 'Seus Dados',
    'appointments.summary': 'Resumo da sua consulta',
    'appointments.fullName': 'Nome completo',
    'appointments.fullNamePlaceholder': 'Seu nome completo',
    'appointments.phone': 'Telefone',
    'appointments.phonePlaceholder': 'Seu número de telefone',
    'appointments.email': 'E-mail',
    'appointments.emailPlaceholder': 'voce@email.com',
    'appointments.referralCode': 'Código de Indicação',
    'appointments.referralPlaceholder': 'REF-XXXXXXXX',
    'appointments.referralOptional': '(opcional)',
    'appointments.referralHint': 'Tem um código de indicação? Ganhe 5% de desconto',
    'appointments.validCode': 'Código válido! Você receberá 5% de desconto',
    'appointments.invalidCode': 'Código inválido',
    'appointments.available': 'Disponível',
    'appointments.selected': 'Selecionado',
    'appointments.booked': 'Ocupado',
    'appointments.back': 'Voltar',
    'appointments.continue': 'Continuar',
    'appointments.confirm': 'Confirmar Consulta',
    'appointments.confirming': 'Confirmando...',
    'appointments.confirmed': 'Consulta Confirmada!',
    'appointments.confirmationEmail': 'Enviamos um e-mail de confirmação para',
    'appointments.bookAnother': 'Agendar outra consulta',
    'appointments.discountApplied': 'Enviamos um e-mail. Você tem 5% de desconto com seu código de indicação!',
    'appointments.hrs': 'hrs',
    
    // Confirmation Screen
    'confirmation.title': 'Reserva Concluída!',
    'confirmation.subtitle': 'Sua consulta foi agendada com sucesso',
    'confirmation.emailSent': 'Enviamos um e-mail de confirmação para',
    'confirmation.createAccount': 'Crie sua conta de paciente',
    'confirmation.createAccountDesc': 'Acesse seu histórico, próximas consultas e mais',
    'confirmation.password': 'Crie uma senha',
    'confirmation.passwordPlaceholder': 'Mínimo 6 caracteres',
    'confirmation.register': 'Criar minha conta',
    'confirmation.registering': 'Criando conta...',
    'confirmation.skipForNow': 'Pular por agora',
    'confirmation.accountCreated': 'Conta criada com sucesso!',
    'confirmation.accountCreatedDesc': 'Agora você pode acessar seu portal de paciente',
    'confirmation.goToPortal': 'Ir para Meu Portal',
    
    // Locations
    'locations.badge': 'Unidades',
    'locations.title': 'Encontre sua',
    'locations.titleHighlight': 'clínica mais próxima',
    'locations.subtitle': 'Com 5 localizações estratégicas em Nayarit e Jalisco, sempre há uma clínica NovellDent perto de você.',
    'locations.viewMap': 'Ver mapa completo',
    'locations.hours': 'Seg - Sáb: 9:00 - 19:00',
    'locations.directions': 'Como chegar',
    
    // Contact
    'contact.badge': 'Contato',
    'contact.title': 'Pronto para',
    'contact.titleHighlight': 'transformar seu sorriso',
    'contact.subtitle': 'Estamos aqui para responder todas as suas perguntas. Entre em contato e agende sua consulta hoje.',
    'contact.callUs': 'Ligue para nós',
    'contact.whatsapp': 'WhatsApp',
    'contact.email': 'E-mail',
    'contact.formTitle': 'Agende sua Consulta',
    'contact.name': 'Nome',
    'contact.namePlaceholder': 'Seu nome',
    'contact.phonePlaceholder': 'Seu telefone',
    'contact.emailPlaceholder': 'voce@email.com',
    'contact.service': 'Serviço de interesse',
    'contact.servicePlaceholder': 'Ex: Clareamento dental',
    'contact.message': 'Mensagem',
    'contact.messagePlaceholder': 'Conte-nos sobre seu caso...',
    'contact.send': 'Enviar Mensagem',
    'contact.sending': 'Enviando...',
    'contact.sent': 'Mensagem enviada!',
    'contact.sentDesc': 'Entraremos em contato em breve.',
    
    // Footer
    'footer.description': 'NovellDent Digital Dentistry. Tecnologia de ponta para seu sorriso perfeito.',
    'footer.services': 'Serviços',
    'footer.generalDentistry': 'Odontologia Geral',
    'footer.whitening': 'Clareamento',
    'footer.implants': 'Implantes',
    'footer.orthodontics': 'Ortodontia',
    'footer.aesthetics': 'Estética Dental',
    'footer.specialties': 'Especialidades',
    'footer.endodontics': 'Endodontia',
    'footer.periodontics': 'Periodontia',
    'footer.oralSurgery': 'Cirurgia Oral',
    'footer.pediatric': 'Odontopediatria',
    'footer.prosthetics': 'Próteses',
    'footer.contact': 'Contato',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos e Condições',
    
    // Auth
    'auth.login': 'Entrar',
    'auth.register': 'Registrar',
    'auth.email': 'E-mail',
    'auth.password': 'Senha',
    'auth.fullName': 'Nome completo',
    'auth.phone': 'Telefone',
    'auth.continue': 'Continuar',
    'auth.createAccount': 'Criar conta',
    'auth.welcome': 'Bem-vindo',
    'auth.accessPortal': 'Acesse seu portal dental',
    'auth.joinUs': 'Junte-se à NovellDent',
    'auth.patient': 'Paciente',
    'auth.doctor': 'Médico',
    'auth.experience': 'Experiência dental de primeira classe',
    
    // ChatBot
    'chatbot.title': 'Denti',
    'chatbot.subtitle': 'Seu assistente dental 🦷',
    'chatbot.greeting': 'Olá! 👋',
    'chatbot.greetingText': 'Sou Denti, seu assistente virtual. Como posso ajudar?',
    'chatbot.placeholder': 'Digite sua mensagem...',
    'chatbot.typing': 'Digitando...',
    'chatbot.services': 'Serviços',
    'chatbot.branches': 'Unidades',
    'chatbot.appointment': 'Consulta',
    'chatbot.prices': 'Preços',
    'chatbot.servicesQ': 'Quais serviços vocês oferecem?',
    'chatbot.branchesQ': 'Quais são suas unidades e horários?',
    'chatbot.appointmentQ': 'Como posso agendar uma consulta?',
    'chatbot.pricesQ': 'Quais são os preços?',
    
    // Dashboard Common
    'dashboard.appointments': 'Consultas',
    'dashboard.calendar': 'Calendário',
    'dashboard.doctors': 'Médicos',
    'dashboard.analytics': 'Analytics',
    'dashboard.metrics': 'Métricas',
    'dashboard.reviews': 'Avaliações',
    'dashboard.files': 'Arquivos',
    'dashboard.prescriptions': 'Receitas',
    'dashboard.documents': 'Documentos',
    'dashboard.referrals': 'Indicações',
    'dashboard.xrayAI': 'RX IA',
    'dashboard.aiReports': 'Relatórios IA',
    'dashboard.simulator': 'Simulador',
    'dashboard.contactCenter': 'Contact Center',
    'dashboard.internalChat': 'Chat Interno',
    'dashboard.logout': 'Sair',
    'dashboard.total': 'Total de Consultas',
    'dashboard.pending': 'Pendentes',
    'dashboard.confirmed': 'Confirmadas',
    'dashboard.today': 'Hoje',
    'dashboard.tomorrow': 'Amanhã',
    'dashboard.noAppointments': 'Sem consultas',
    'dashboard.noAppointmentsFiltered': 'Nenhuma consulta encontrada com os filtros selecionados.',
    'dashboard.noAppointmentsYet': 'Nenhuma consulta agendada ainda.',
    'dashboard.loading': 'Carregando consultas...',
    'dashboard.searchPlaceholder': 'Buscar por nome, e-mail ou telefone...',
    'dashboard.all': 'Todos',
    'dashboard.allLocations': 'Todas',
    'dashboard.status': 'Status',
    'dashboard.branch': 'Unidade',
    
    // Admin Dashboard
    'admin.title': 'Painel de Administração',
    'admin.completed': 'Concluídas',
    'admin.cancelled': 'Canceladas',
    
    // Doctor Dashboard
    'doctor.title': 'Portal do Médico',
    'doctor.todayAppointments': 'Consultas Hoje',
    'doctor.activeTreatments': 'Tratamentos Ativos',
    'doctor.thisWeek': 'Esta Semana',
    'doctor.weeklyCalendar': 'Calendário Semanal',
    'doctor.appointmentsOf': 'Consultas de',
    'doctor.noAppointmentsDay': 'Sem consultas para este dia',
    'doctor.patients': 'Pacientes',
    'doctor.treatments': 'Tratamentos',
    'doctor.complete': 'Concluir',
    
    // Common
    'common.loading': 'Carregando...',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.print': 'Imprimir',
    
    // Brands Section
    'brands.title': 'Marcas que Usamos',
    'brands.subtitle': 'Trabalhamos com as melhores marcas de tecnologia dental do mundo',
    
    // Technology Section
    'technology.title': 'A Melhor Tecnologia',
    'technology.subtitle': 'Utilizamos equipamentos e software de ponta para oferecer os melhores resultados',
    'technology.precision': 'Precisão Digital',
    'technology.precisionDesc': 'Escaneamento 3D intraoral para restaurações exatas',
    'technology.speed': 'Rapidez',
    'technology.speedDesc': 'Design e fabricação no mesmo dia',
    'technology.quality': 'Qualidade Superior',
    'technology.qualityDesc': 'Materiais de última geração certificados',
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.about': 'О Нас',
    'nav.specialties': 'Специальности',
    'nav.services': 'Услуги',
    'nav.appointments': 'Запись',
    'nav.locations': 'Адреса',
    'nav.contact': 'Контакты',
    'nav.login': 'Войти',
    'nav.portal': 'Мой Портал',
    'nav.bookNow': 'Записаться',
    
    // Hero
    'hero.badge': 'Передовая Цифровая Стоматология',
    'hero.title1': 'Ваша улыбка.',
    'hero.title2': 'Совершенна.',
    'hero.specialistsIn': 'Специалисты по',
    'hero.service1': 'Зубные Импланты',
    'hero.service2': 'Невидимая Ортодонтия',
    'hero.service3': 'Отбеливание',
    'hero.service4': 'Дизайн Улыбки',
    'hero.cta': 'Записаться',
    'hero.secondary': 'Узнать Больше',
    'hero.years': 'Лет',
    'hero.branches': 'Филиалов',
    'hero.specialties': 'Специальностей',
    'hero.patients': 'Пациентов',
    
    // About
    'about.badge': 'О Нас',
    'about.title1': 'Совершенство в',
    'about.title2': 'Цифровой Стоматологии',
    'about.description': 'В <strong>NovellDent</strong> мы стремимся предоставить вам лучший опыт в стоматологическом здоровье с передовыми технологиями и командой специалистов, преданных вашему благополучию.',
    'about.yearsExperience': 'Лет опыта',
    'about.feature1.title': 'Цифровые Технологии',
    'about.feature1.desc': 'Современное оборудование для точной диагностики.',
    'about.feature2.title': 'Полная Безопасность',
    'about.feature2.desc': 'Строгие протоколы гигиены и биобезопасности.',
    'about.feature3.title': 'Сертифицированные',
    'about.feature3.desc': 'Специалисты с большим опытом и постоянным обучением.',
    'about.feature4.title': 'Персонализация',
    'about.feature4.desc': 'Лечение, разработанное специально для вас.',
    
    // Services
    'services.badge': 'Услуги',
    'services.title': 'Преображающие результаты',
    'services.subtitle': 'Лечение с точным планированием для достижения оптимальных результатов.',
    'services.whitening': 'Отбеливание',
    'services.whitening.desc': 'Восстановите естественную белизну зубов с профессиональной LED технологией.',
    'services.whitening.f1': 'Мгновенный результат',
    'services.whitening.f2': 'Без чувствительности',
    'services.implants': 'Импланты',
    'services.implants.desc': 'Замена зубов высококачественными титановыми имплантами.',
    'services.implants.f1': 'Биосовместимые',
    'services.implants.f2': 'Долговечные',
    'services.orthodontics': 'Ортодонтия',
    'services.orthodontics.desc': 'Прозрачные элайнеры для незаметной коррекции улыбки.',
    'services.orthodontics.f1': 'Почти невидимые',
    'services.orthodontics.f2': 'Съёмные',
    'services.smileDesign': 'Дизайн Улыбки',
    'services.smileDesign.desc': 'Полное преображение с винирами и эстетическими техниками.',
    'services.smileDesign.f1': 'Персонализация',
    'services.smileDesign.f2': 'Естественный результат',
    'services.schedule': 'Записаться',
    
    // Specialties
    'specialties.badge': 'Специальности',
    'specialties.title': 'Эксперты в каждой области',
    'specialties.subtitle': 'Многопрофильная команда для полной и точной диагностики.',
    'specialties.general': 'Общая Стоматология',
    'specialties.endodontics': 'Эндодонтия',
    'specialties.implantology': 'Имплантология',
    'specialties.maxillofacial': 'Челюстно-лицевая Эстетика',
    'specialties.orthodontics': 'Ортодонтия',
    'specialties.pediatric': 'Детская Стоматология',
    'specialties.prosthetics': 'Зубное Протезирование',
    'specialties.surgery': 'Хирургия Полости Рта',
    'specialties.aesthetics': 'Эстетическая Стоматология',
    
    // Testimonials
    'testimonials.badge': 'Отзывы',
    'testimonials.title': 'Что говорят',
    'testimonials.titleHighlight': 'наши пациенты',
    'testimonials.subtitle': 'Реальные истории людей, преобразивших улыбку с нами.',
    'testimonials.patientSince': 'Пациент с',
    
    // Reviews
    'reviews.badge': 'Отзывы Пациентов',
    'reviews.title': 'Что говорят',
    'reviews.titleHighlight': 'наши пациенты',
    'reviews.reviews': 'отзывов',
    
    // CTA
    'cta.title': 'Ваша новая улыбка ждёт вас',
    'cta.subtitle': 'Запишитесь на бесплатную консультацию и узнайте, как мы можем преобразить вашу улыбку с лучшими стоматологическими технологиями.',
    'cta.button': 'Записаться Бесплатно',
    'cta.call': 'Позвонить',
    
    // Appointments
    'appointments.badge': 'Онлайн Запись',
    'appointments.title': 'Запишитесь на',
    'appointments.titleHighlight': 'приём сейчас',
    'appointments.subtitle': 'Запишитесь на приём онлайн быстро и легко. Выберите филиал, дату и время.',
    'appointments.step.branch': 'Филиал',
    'appointments.step.date': 'Дата',
    'appointments.step.time': 'Время',
    'appointments.step.data': 'Данные',
    'appointments.selectBranch': 'Выберите Филиал',
    'appointments.serviceType': 'Тип Услуги',
    'appointments.selectService': 'Выберите услугу',
    'appointments.selectDate': 'Выберите Дату',
    'appointments.selectTime': 'Выберите Доступное Время',
    'appointments.loadingSlots': 'Загрузка расписания...',
    'appointments.noSlots': 'Нет доступного времени для этой даты и филиала.',
    'appointments.selectAnotherDate': 'Выбрать другую дату',
    'appointments.morning': 'Утро',
    'appointments.afternoon': 'День',
    'appointments.yourData': 'Ваши Данные',
    'appointments.summary': 'Детали записи',
    'appointments.fullName': 'Полное имя',
    'appointments.fullNamePlaceholder': 'Ваше полное имя',
    'appointments.phone': 'Телефон',
    'appointments.phonePlaceholder': 'Ваш номер телефона',
    'appointments.email': 'Электронная почта',
    'appointments.emailPlaceholder': 'вы@email.com',
    'appointments.referralCode': 'Реферальный Код',
    'appointments.referralPlaceholder': 'REF-XXXXXXXX',
    'appointments.referralOptional': '(необязательно)',
    'appointments.referralHint': 'Есть реферальный код? Получите скидку 5%',
    'appointments.validCode': 'Код действителен! Вы получите скидку 5%',
    'appointments.invalidCode': 'Недействительный код',
    'appointments.available': 'Доступно',
    'appointments.selected': 'Выбрано',
    'appointments.booked': 'Занято',
    'appointments.back': 'Назад',
    'appointments.continue': 'Продолжить',
    'appointments.confirm': 'Подтвердить Запись',
    'appointments.confirming': 'Подтверждение...',
    'appointments.confirmed': 'Запись Подтверждена!',
    'appointments.confirmationEmail': 'Мы отправили подтверждение на',
    'appointments.bookAnother': 'Записаться ещё раз',
    'appointments.discountApplied': 'Мы отправили вам письмо. У вас скидка 5% по реферальному коду!',
    'appointments.hrs': 'ч',
    
    // Confirmation Screen
    'confirmation.title': 'Запись Завершена!',
    'confirmation.subtitle': 'Ваш приём успешно запланирован',
    'confirmation.emailSent': 'Мы отправили подтверждение на',
    'confirmation.createAccount': 'Создайте аккаунт пациента',
    'confirmation.createAccountDesc': 'Получите доступ к истории, предстоящим визитам и многому другому',
    'confirmation.password': 'Создайте пароль',
    'confirmation.passwordPlaceholder': 'Минимум 6 символов',
    'confirmation.register': 'Создать аккаунт',
    'confirmation.registering': 'Создание аккаунта...',
    'confirmation.skipForNow': 'Пропустить',
    'confirmation.accountCreated': 'Аккаунт успешно создан!',
    'confirmation.accountCreatedDesc': 'Теперь вы можете войти в портал пациента',
    'confirmation.goToPortal': 'Перейти в Портал',
    
    // Locations
    'locations.badge': 'Адреса',
    'locations.title': 'Найдите',
    'locations.titleHighlight': 'ближайшую клинику',
    'locations.subtitle': 'С 5 стратегическими локациями в Наярит и Халиско, клиника NovellDent всегда рядом.',
    'locations.viewMap': 'Посмотреть карту',
    'locations.hours': 'Пн - Сб: 9:00 - 19:00',
    'locations.directions': 'Как добраться',
    
    // Contact
    'contact.badge': 'Контакты',
    'contact.title': 'Готовы',
    'contact.titleHighlight': 'преобразить улыбку',
    'contact.subtitle': 'Мы здесь, чтобы ответить на все ваши вопросы. Свяжитесь с нами и запишитесь сегодня.',
    'contact.callUs': 'Позвоните нам',
    'contact.whatsapp': 'WhatsApp',
    'contact.email': 'Почта',
    'contact.formTitle': 'Записаться на Приём',
    'contact.name': 'Имя',
    'contact.namePlaceholder': 'Ваше имя',
    'contact.phonePlaceholder': 'Ваш телефон',
    'contact.emailPlaceholder': 'вы@email.com',
    'contact.service': 'Интересующая услуга',
    'contact.servicePlaceholder': 'Напр: Отбеливание зубов',
    'contact.message': 'Сообщение',
    'contact.messagePlaceholder': 'Расскажите о вашем случае...',
    'contact.send': 'Отправить',
    'contact.sending': 'Отправка...',
    'contact.sent': 'Сообщение отправлено!',
    'contact.sentDesc': 'Мы свяжемся с вами в ближайшее время.',
    
    // Footer
    'footer.description': 'NovellDent Digital Dentistry. Передовые технологии для идеальной улыбки.',
    'footer.services': 'Услуги',
    'footer.generalDentistry': 'Общая Стоматология',
    'footer.whitening': 'Отбеливание',
    'footer.implants': 'Импланты',
    'footer.orthodontics': 'Ортодонтия',
    'footer.aesthetics': 'Эстетическая Стоматология',
    'footer.specialties': 'Специальности',
    'footer.endodontics': 'Эндодонтия',
    'footer.periodontics': 'Пародонтология',
    'footer.oralSurgery': 'Хирургия Полости Рта',
    'footer.pediatric': 'Детская Стоматология',
    'footer.prosthetics': 'Протезирование',
    'footer.contact': 'Контакты',
    'footer.rights': 'Все права защищены.',
    'footer.privacy': 'Политика Конфиденциальности',
    'footer.terms': 'Условия Использования',
    
    // Auth
    'auth.login': 'Войти',
    'auth.register': 'Регистрация',
    'auth.email': 'Электронная почта',
    'auth.password': 'Пароль',
    'auth.fullName': 'Полное имя',
    'auth.phone': 'Телефон',
    'auth.continue': 'Продолжить',
    'auth.createAccount': 'Создать аккаунт',
    'auth.welcome': 'Добро пожаловать',
    'auth.accessPortal': 'Войдите в свой портал',
    'auth.joinUs': 'Присоединяйтесь к NovellDent',
    'auth.patient': 'Пациент',
    'auth.doctor': 'Врач',
    'auth.experience': 'Стоматологический опыт первого класса',
    
    // ChatBot
    'chatbot.title': 'Denti',
    'chatbot.subtitle': 'Ваш стоматологический помощник 🦷',
    'chatbot.greeting': 'Привет! 👋',
    'chatbot.greetingText': 'Я Denti, ваш виртуальный помощник. Чем могу помочь?',
    'chatbot.placeholder': 'Введите сообщение...',
    'chatbot.typing': 'Печатает...',
    'chatbot.services': 'Услуги',
    'chatbot.branches': 'Адреса',
    'chatbot.appointment': 'Запись',
    'chatbot.prices': 'Цены',
    'chatbot.servicesQ': 'Какие услуги вы предоставляете?',
    'chatbot.branchesQ': 'Какие у вас адреса и часы работы?',
    'chatbot.appointmentQ': 'Как записаться на приём?',
    'chatbot.pricesQ': 'Какие у вас цены?',
    
    // Dashboard Common
    'dashboard.appointments': 'Записи',
    'dashboard.calendar': 'Календарь',
    'dashboard.doctors': 'Врачи',
    'dashboard.analytics': 'Аналитика',
    'dashboard.metrics': 'Метрики',
    'dashboard.reviews': 'Отзывы',
    'dashboard.files': 'Файлы',
    'dashboard.prescriptions': 'Рецепты',
    'dashboard.documents': 'Документы',
    'dashboard.referrals': 'Рефералы',
    'dashboard.xrayAI': 'Рентген ИИ',
    'dashboard.aiReports': 'Отчёты ИИ',
    'dashboard.simulator': 'Симулятор',
    'dashboard.contactCenter': 'Контакт Центр',
    'dashboard.internalChat': 'Внутренний Чат',
    'dashboard.logout': 'Выйти',
    'dashboard.total': 'Всего Записей',
    'dashboard.pending': 'Ожидают',
    'dashboard.confirmed': 'Подтверждены',
    'dashboard.today': 'Сегодня',
    'dashboard.tomorrow': 'Завтра',
    'dashboard.noAppointments': 'Нет записей',
    'dashboard.noAppointmentsFiltered': 'Записи не найдены по выбранным фильтрам.',
    'dashboard.noAppointmentsYet': 'Записей пока нет.',
    'dashboard.loading': 'Загрузка записей...',
    'dashboard.searchPlaceholder': 'Поиск по имени, email или телефону...',
    'dashboard.all': 'Все',
    'dashboard.allLocations': 'Все',
    'dashboard.status': 'Статус',
    'dashboard.branch': 'Филиал',
    
    // Admin Dashboard
    'admin.title': 'Панель Администратора',
    'admin.completed': 'Завершены',
    'admin.cancelled': 'Отменены',
    
    // Doctor Dashboard
    'doctor.title': 'Портал Врача',
    'doctor.todayAppointments': 'Записей Сегодня',
    'doctor.activeTreatments': 'Активные Лечения',
    'doctor.thisWeek': 'На Этой Неделе',
    'doctor.weeklyCalendar': 'Недельный Календарь',
    'doctor.appointmentsOf': 'Записи на',
    'doctor.noAppointmentsDay': 'Нет записей на этот день',
    'doctor.patients': 'Пациенты',
    'doctor.treatments': 'Лечения',
    'doctor.complete': 'Завершить',
    
    // Common
    'common.loading': 'Загрузка...',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.view': 'Просмотр',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.export': 'Экспорт',
    'common.print': 'Печать',
    
    // Brands Section
    'brands.title': 'Бренды, которые мы используем',
    'brands.subtitle': 'Мы работаем с лучшими мировыми брендами стоматологических технологий',
    
    // Technology Section
    'technology.title': 'Лучшие Технологии',
    'technology.subtitle': 'Мы используем передовое оборудование и программное обеспечение для достижения лучших результатов',
    'technology.precision': 'Цифровая Точность',
    'technology.precisionDesc': 'Внутриротовое 3D-сканирование для точных реставраций',
    'technology.speed': 'Скорость',
    'technology.speedDesc': 'Проектирование и изготовление в тот же день',
    'technology.quality': 'Высшее Качество',
    'technology.qualityDesc': 'Сертифицированные материалы нового поколения',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguageState] = useState<Language>('es');

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved && translations[saved]) {
      setLanguageState(saved);
      document.documentElement.lang = saved;
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    document.documentElement.lang = lang;
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['es'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
