import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'es' | 'en' | 'pt' | 'ru';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.specialties': 'Categorías',
    'nav.services': 'Productos',
    'nav.appointments': 'Tienda',
    'nav.locations': '¿Dónde Estamos?',
    'nav.contact': 'Contacto',
    'nav.login': 'Iniciar Sesión',
    'nav.portal': 'Mi Cuenta',
    'nav.bookNow': 'Comprar Ahora',
    
    // Hero
    'hero.badge': '✨ Tradición desde 1985',
    'hero.title1': 'Tradición, Calidad y',
    'hero.title2': 'Bienestar Natural',
    'hero.specialistsIn': 'Especialistas en',
    'hero.service1': 'Jarabes Naturales',
    'hero.service2': 'Pomadas Medicinales',
    'hero.service3': 'Aceites Esenciales',
    'hero.service4': 'Productos de Rebotica',
    'hero.cta': 'Comprar Ahora',
    'hero.secondary': 'Conocer Más',
    'hero.years': 'Años',
    'hero.branches': 'Categorías',
    'hero.specialties': 'Productos',
    'hero.patients': 'Clientes',
    'hero.description': 'Somos una empresa 100% mexicana con más de 40 años de experiencia en la fabricación, envasado y distribución de jarabes para la tos, pomadas, aceites y productos de rebotica tradicional.',
    
    // About
    'about.badge': 'Quiénes Somos',
    'about.title1': 'Tradición y Calidad',
    'about.title2': 'Desde 1985',
    'about.description': 'En <strong>Productos Camacho</strong>, somos una empresa 100% mexicana con más de 40 años de experiencia en la fabricación, envasado y distribución de <strong>jarabes para la tos</strong>, <strong>pomadas</strong>, <strong>aceites</strong> y productos de <strong>rebotica tradicional</strong>. Fundada en el Estado de México en 1985, nuestra misión es preservar las fórmulas magistrales de la botica clásica, combinando tradición con innovación para cuidar la salud de las familias mexicanas.',
    'about.yearsExperience': 'Años de tradición',
    'about.feature1.title': 'Ingredientes Naturales',
    'about.feature1.desc': 'Formulados con ingredientes de origen natural y eficacia comprobada.',
    'about.feature2.title': 'Calidad Garantizada',
    'about.feature2.desc': 'Procesos de fabricación rigurosos que garantizan la calidad.',
    'about.feature3.title': 'Tradición Mexicana',
    'about.feature3.desc': 'Preservamos las fórmulas magistrales de la botica clásica.',
    'about.feature4.title': 'Distribución Nacional',
    'about.feature4.desc': 'Llegamos a farmacias independientes y negocios naturistas.',
    
    // Services/Products
    'services.badge': 'Nuestros Productos',
    'services.title': 'Calidad que se siente',
    'services.subtitle': 'Productos naturales con eficacia comprobada para el bienestar de tu familia.',
    'services.whitening': 'Jarabes',
    'services.whitening.desc': 'Jarabes naturales para la tos como AJOLOTIUS® y BRONCOPLUS® con ingredientes de eficacia comprobada.',
    'services.whitening.f1': 'Ingredientes naturales',
    'services.whitening.f2': 'Eficacia comprobada',
    'services.implants': 'Pomadas',
    'services.implants.desc': 'Pomadas medicinales elaboradas con fórmulas tradicionales para diversos usos.',
    'services.implants.f1': 'Fórmulas tradicionales',
    'services.implants.f2': 'Múltiples beneficios',
    'services.orthodontics': 'Aceites',
    'services.orthodontics.desc': 'Aceites esenciales y naturales de la más alta calidad para uso tópico.',
    'services.orthodontics.f1': '100% Naturales',
    'services.orthodontics.f2': 'Alta pureza',
    'services.smileDesign': 'Productos de Rebotica',
    'services.smileDesign.desc': 'Productos tradicionales de farmacia como químicos, lociones y más.',
    'services.smileDesign.f1': 'Recetas magistrales',
    'services.smileDesign.f2': 'Tradición mexicana',
    'services.schedule': 'Ver Producto',
    
    // Specialties/Categories
    'specialties.badge': 'Categorías',
    'specialties.title': 'Explora nuestro catálogo',
    'specialties.subtitle': 'Más de 165 productos naturales para el cuidado de tu salud y bienestar.',
    'specialties.general': 'Aceites',
    'specialties.endodontics': 'Pomadas',
    'specialties.implantology': 'Jarabes',
    'specialties.maxillofacial': 'Lociones',
    'specialties.orthodontics': 'Vinos',
    'specialties.pediatric': 'Químicos',
    'specialties.prosthetics': 'Botánicos',
    'specialties.surgery': 'Bálsamos',
    'specialties.aesthetics': 'Glicerinas',
    
    // Brands Section
    'brands.title': 'Nuestras Marcas Registradas',
    'brands.subtitle': 'Marcas reconocidas con ingredientes naturales y eficacia comprobada',
    
    // Technology Section
    'technology.title': 'Nuestras Marcas',
    'technology.subtitle': 'Contamos con marcas registradas y reconocidas como AJOLOTIUS® y BRONCOPLUS®',
    'technology.precision': 'AJOLOTIUS®',
    'technology.precisionDesc': 'Jarabe natural para la tos con fórmula tradicional mexicana',
    'technology.speed': 'BRONCOPLUS®',
    'technology.speedDesc': 'Jarabe bronquial con ingredientes naturales de eficacia comprobada',
    'technology.quality': 'Calidad Premium',
    'technology.qualityDesc': 'Productos aliados de farmacias independientes, distribuidores mayoristas y negocios naturistas',
    
    // Testimonials
    'testimonials.badge': 'Testimonios',
    'testimonials.title': 'Lo que dicen',
    'testimonials.titleHighlight': 'nuestros clientes',
    'testimonials.subtitle': 'Historias reales de clientes que confían en nuestros productos.',
    'testimonials.patientSince': 'Cliente desde',
    
    // Reviews
    'reviews.badge': 'Opiniones de Clientes',
    'reviews.title': 'Lo que dicen',
    'reviews.titleHighlight': 'nuestros clientes',
    'reviews.reviews': 'reseñas',
    
    // CTA
    'cta.title': 'Tu bienestar nos importa',
    'cta.subtitle': 'Descubre nuestra línea completa de productos naturales. Más de 40 años cuidando la salud de las familias mexicanas.',
    'cta.button': 'Ver Catálogo',
    'cta.call': 'Llamar Ahora',
    
    // Appointments/Shop
    'appointments.badge': 'Tienda en Línea',
    'appointments.title': 'Compra',
    'appointments.titleHighlight': 'ahora',
    'appointments.subtitle': 'Compra en línea de forma rápida y sencilla. Envío a toda la República Mexicana.',
    'appointments.step.branch': 'Categoría',
    'appointments.step.date': 'Productos',
    'appointments.step.time': 'Carrito',
    'appointments.step.data': 'Pago',
    'appointments.selectBranch': 'Selecciona una Categoría',
    'appointments.serviceType': 'Tipo de Producto',
    'appointments.selectService': 'Selecciona un producto',
    'appointments.selectDate': 'Selecciona Productos',
    'appointments.selectTime': 'Añade al Carrito',
    'appointments.loadingSlots': 'Cargando productos...',
    'appointments.noSlots': 'No hay productos disponibles en esta categoría.',
    'appointments.selectAnotherDate': 'Ver otra categoría',
    'appointments.morning': 'Más vendidos',
    'appointments.afternoon': 'Nuevos',
    'appointments.yourData': 'Tus Datos de Envío',
    'appointments.summary': 'Resumen de tu pedido',
    'appointments.fullName': 'Nombre completo',
    'appointments.fullNamePlaceholder': 'Tu nombre completo',
    'appointments.phone': 'Teléfono',
    'appointments.phonePlaceholder': 'Tu número de teléfono',
    'appointments.email': 'Correo electrónico',
    'appointments.emailPlaceholder': 'tu@email.com',
    'appointments.referralCode': 'Código de Descuento',
    'appointments.referralPlaceholder': 'DESCUENTO10',
    'appointments.referralOptional': '(opcional)',
    'appointments.referralHint': '¿Tienes un código de descuento?',
    'appointments.validCode': '¡Código válido! Obtuviste descuento',
    'appointments.invalidCode': 'Código no válido',
    'appointments.available': 'Disponible',
    'appointments.selected': 'Seleccionado',
    'appointments.booked': 'Agotado',
    'appointments.back': 'Atrás',
    'appointments.continue': 'Continuar',
    'appointments.confirm': 'Confirmar Pedido',
    'appointments.confirming': 'Procesando...',
    'appointments.confirmed': '¡Pedido Confirmado!',
    'appointments.confirmationEmail': 'Te hemos enviado un correo de confirmación a',
    'appointments.bookAnother': 'Hacer otro pedido',
    'appointments.discountApplied': 'Te hemos enviado un correo. ¡Obtuviste descuento en tu compra!',
    'appointments.hrs': '',
    
    // Locations
    'locations.badge': '¿Dónde nos encontramos?',
    'locations.title': 'Encuentra',
    'locations.titleHighlight': 'nuestros productos',
    'locations.subtitle': 'Nuestros productos están disponibles en farmacias independientes, distribuidores mayoristas y negocios naturistas en toda la República Mexicana.',
    'locations.viewMap': 'Ver mapa',
    'locations.hours': 'Lun - Vie: 9:00 - 18:00',
    'locations.directions': 'Cómo llegar',
    
    // Contact
    'contact.badge': 'Contacto',
    'contact.title': '¿Listo para',
    'contact.titleHighlight': 'probar nuestros productos',
    'contact.subtitle': 'Estamos aquí para responder todas tus preguntas. Contáctanos para pedidos mayoristas o información general.',
    'contact.callUs': 'Llámanos',
    'contact.whatsapp': 'WhatsApp',
    'contact.email': 'Email',
    'contact.formTitle': 'Contáctanos',
    'contact.name': 'Nombre',
    'contact.namePlaceholder': 'Tu nombre',
    'contact.phonePlaceholder': 'Tu teléfono',
    'contact.emailPlaceholder': 'tu@email.com',
    'contact.service': 'Producto de interés',
    'contact.servicePlaceholder': 'Ej: Jarabe AJOLOTIUS®',
    'contact.message': 'Mensaje',
    'contact.messagePlaceholder': 'Cuéntanos sobre tu consulta...',
    'contact.send': 'Enviar Mensaje',
    'contact.sending': 'Enviando...',
    'contact.sent': '¡Mensaje enviado!',
    'contact.sentDesc': 'Nos pondremos en contacto contigo pronto.',
    
    // Footer
    'footer.description': 'Productos Camacho. Tradición, calidad y bienestar natural desde 1985.',
    'footer.services': 'Productos',
    'footer.generalDentistry': 'Aceites Naturales',
    'footer.whitening': 'Pomadas Medicinales',
    'footer.implants': 'Jarabes para Tos',
    'footer.orthodontics': 'Lociones',
    'footer.aesthetics': 'Productos de Rebotica',
    'footer.specialties': 'Categorías',
    'footer.endodontics': 'Químicos',
    'footer.periodontics': 'Botánicos',
    'footer.oralSurgery': 'Bálsamos',
    'footer.pediatric': 'Vinos Medicinales',
    'footer.prosthetics': 'Glicerinas',
    'footer.contact': 'Contacto',
    'footer.rights': 'Todos los derechos reservados.',
    'footer.privacy': 'Aviso de Privacidad',
    'footer.terms': 'Términos y Condiciones',
    
    // Auth
    'auth.login': 'Iniciar Sesión',
    'auth.register': 'Registrarse',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.fullName': 'Nombre completo',
    'auth.phone': 'Teléfono',
    'auth.continue': 'Continuar',
    'auth.createAccount': 'Crear cuenta',
    'auth.welcome': 'Bienvenido',
    'auth.accessPortal': 'Accede a tu cuenta',
    'auth.joinUs': 'Únete a Productos Camacho',
    'auth.patient': 'Cliente',
    'auth.doctor': 'Distribuidor',
    'auth.experience': 'Productos naturales de calidad',
    
    // ChatBot
    'chatbot.title': 'Camacho',
    'chatbot.subtitle': 'Tu asistente de salud 🌿',
    'chatbot.greeting': '¡Hola! 👋',
    'chatbot.greetingText': 'Soy tu asistente virtual. ¿En qué puedo ayudarte?',
    'chatbot.placeholder': 'Escribe tu mensaje...',
    'chatbot.typing': 'Escribiendo...',
    'chatbot.services': 'Productos',
    'chatbot.branches': 'Ubicación',
    'chatbot.appointment': 'Pedido',
    'chatbot.prices': 'Precios',
    'chatbot.servicesQ': '¿Qué productos tienen?',
    'chatbot.branchesQ': '¿Dónde puedo comprar sus productos?',
    'chatbot.appointmentQ': '¿Cómo puedo hacer un pedido?',
    'chatbot.pricesQ': '¿Cuáles son sus precios mayoreo?',
    
    // Dashboard Common
    'dashboard.appointments': 'Pedidos',
    'dashboard.calendar': 'Calendario',
    'dashboard.doctors': 'Distribuidores',
    'dashboard.analytics': 'Analytics',
    'dashboard.metrics': 'Métricas',
    'dashboard.reviews': 'Reseñas',
    'dashboard.files': 'Archivos',
    'dashboard.prescriptions': 'Facturas',
    'dashboard.documents': 'Documentos',
    'dashboard.referrals': 'Referidos',
    'dashboard.xrayAI': 'IA',
    'dashboard.aiReports': 'Reportes IA',
    'dashboard.simulator': 'Simulador',
    'dashboard.contactCenter': 'Centro de Contacto',
    'dashboard.internalChat': 'Chat Interno',
    'dashboard.logout': 'Cerrar Sesión',
    'dashboard.total': 'Total Pedidos',
    'dashboard.pending': 'Pendientes',
    'dashboard.confirmed': 'Confirmados',
    'dashboard.today': 'Hoy',
    'dashboard.tomorrow': 'Mañana',
    'dashboard.noAppointments': 'No hay pedidos',
    'dashboard.noAppointmentsFiltered': 'No se encontraron pedidos con los filtros seleccionados.',
    'dashboard.noAppointmentsYet': 'Aún no hay pedidos.',
    'dashboard.loading': 'Cargando pedidos...',
    'dashboard.searchPlaceholder': 'Buscar por nombre, email o teléfono...',
    'dashboard.all': 'Todos',
    'dashboard.allLocations': 'Todas',
    'dashboard.status': 'Estado',
    'dashboard.branch': 'Almacén',
    
    // Admin Dashboard
    'admin.title': 'Panel de Administración',
    'admin.completed': 'Completados',
    'admin.cancelled': 'Cancelados',
    
    // Common
    'common.loading': 'Cargando...',
    'common.save': 'Guardar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.print': 'Imprimir',
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About Us',
    'nav.specialties': 'Categories',
    'nav.services': 'Products',
    'nav.appointments': 'Shop',
    'nav.locations': 'Locations',
    'nav.contact': 'Contact',
    'nav.login': 'Login',
    'nav.portal': 'My Account',
    'nav.bookNow': 'Shop Now',
    
    // Hero
    'hero.badge': '✨ Tradition since 1985',
    'hero.title1': 'Tradition, Quality and',
    'hero.title2': 'Natural Wellness',
    'hero.specialistsIn': 'Specialists in',
    'hero.service1': 'Natural Syrups',
    'hero.service2': 'Medicinal Ointments',
    'hero.service3': 'Essential Oils',
    'hero.service4': 'Traditional Pharmacy Products',
    'hero.cta': 'Shop Now',
    'hero.secondary': 'Learn More',
    'hero.years': 'Years',
    'hero.branches': 'Categories',
    'hero.specialties': 'Products',
    'hero.patients': 'Customers',
    'hero.description': 'We are a 100% Mexican company with over 40 years of experience in manufacturing, packaging and distributing cough syrups, ointments, oils and traditional pharmacy products.',
    
    // About
    'about.badge': 'About Us',
    'about.title1': 'Tradition & Quality',
    'about.title2': 'Since 1985',
    'about.description': 'At <strong>Productos Camacho</strong>, we are a 100% Mexican company with over 40 years of experience in manufacturing, packaging and distributing <strong>cough syrups</strong>, <strong>ointments</strong>, <strong>oils</strong> and <strong>traditional pharmacy products</strong>. Founded in the State of Mexico in 1985, our mission is to preserve the master formulas of the classic apothecary, combining tradition with innovation to care for the health of Mexican families.',
    'about.yearsExperience': 'Years of tradition',
    'about.feature1.title': 'Natural Ingredients',
    'about.feature1.desc': 'Formulated with natural ingredients of proven efficacy.',
    'about.feature2.title': 'Guaranteed Quality',
    'about.feature2.desc': 'Rigorous manufacturing processes that guarantee quality.',
    'about.feature3.title': 'Mexican Tradition',
    'about.feature3.desc': 'We preserve the master formulas of the classic pharmacy.',
    'about.feature4.title': 'National Distribution',
    'about.feature4.desc': 'We reach independent pharmacies and natural health stores.',
    
    // Services/Products
    'services.badge': 'Our Products',
    'services.title': 'Quality you can feel',
    'services.subtitle': 'Natural products with proven efficacy for your family wellness.',
    'services.whitening': 'Syrups',
    'services.whitening.desc': 'Natural cough syrups like AJOLOTIUS® and BRONCOPLUS® with proven efficacy ingredients.',
    'services.whitening.f1': 'Natural ingredients',
    'services.whitening.f2': 'Proven efficacy',
    'services.implants': 'Ointments',
    'services.implants.desc': 'Medicinal ointments made with traditional formulas for various uses.',
    'services.implants.f1': 'Traditional formulas',
    'services.implants.f2': 'Multiple benefits',
    'services.orthodontics': 'Oils',
    'services.orthodontics.desc': 'Essential and natural oils of the highest quality for topical use.',
    'services.orthodontics.f1': '100% Natural',
    'services.orthodontics.f2': 'High purity',
    'services.smileDesign': 'Pharmacy Products',
    'services.smileDesign.desc': 'Traditional pharmacy products like chemicals, lotions and more.',
    'services.smileDesign.f1': 'Master recipes',
    'services.smileDesign.f2': 'Mexican tradition',
    'services.schedule': 'View Product',
    
    // Specialties/Categories
    'specialties.badge': 'Categories',
    'specialties.title': 'Explore our catalog',
    'specialties.subtitle': 'Over 165 natural products for your health and wellness care.',
    'specialties.general': 'Oils',
    'specialties.endodontics': 'Ointments',
    'specialties.implantology': 'Syrups',
    'specialties.maxillofacial': 'Lotions',
    'specialties.orthodontics': 'Wines',
    'specialties.pediatric': 'Chemicals',
    'specialties.prosthetics': 'Botanicals',
    'specialties.surgery': 'Balms',
    'specialties.aesthetics': 'Glycerins',
    
    // Brands Section
    'brands.title': 'Our Registered Trademarks',
    'brands.subtitle': 'Recognized brands with natural ingredients and proven efficacy',
    
    // Technology Section
    'technology.title': 'Our Brands',
    'technology.subtitle': 'We have registered and recognized trademarks like AJOLOTIUS® and BRONCOPLUS®',
    'technology.precision': 'AJOLOTIUS®',
    'technology.precisionDesc': 'Natural cough syrup with traditional Mexican formula',
    'technology.speed': 'BRONCOPLUS®',
    'technology.speedDesc': 'Bronchial syrup with proven natural ingredients',
    'technology.quality': 'Premium Quality',
    'technology.qualityDesc': 'Products allied with independent pharmacies, wholesale distributors and natural health stores',
    
    // Testimonials
    'testimonials.badge': 'Testimonials',
    'testimonials.title': 'What our',
    'testimonials.titleHighlight': 'customers say',
    'testimonials.subtitle': 'Real stories from customers who trust our products.',
    'testimonials.patientSince': 'Customer since',
    
    // Reviews
    'reviews.badge': 'Customer Reviews',
    'reviews.title': 'What our',
    'reviews.titleHighlight': 'customers say',
    'reviews.reviews': 'reviews',
    
    // CTA
    'cta.title': 'Your wellness matters to us',
    'cta.subtitle': 'Discover our complete line of natural products. Over 40 years caring for Mexican families health.',
    'cta.button': 'View Catalog',
    'cta.call': 'Call Now',
    
    // Locations
    'locations.badge': 'Where to find us?',
    'locations.title': 'Find',
    'locations.titleHighlight': 'our products',
    'locations.subtitle': 'Our products are available at independent pharmacies, wholesale distributors and natural health stores throughout Mexico.',
    'locations.viewMap': 'View map',
    'locations.hours': 'Mon - Fri: 9:00 - 18:00',
    'locations.directions': 'Get directions',
    
    // Contact
    'contact.badge': 'Contact',
    'contact.title': 'Ready to',
    'contact.titleHighlight': 'try our products',
    'contact.subtitle': 'We are here to answer all your questions. Contact us for wholesale orders or general information.',
    'contact.callUs': 'Call us',
    'contact.whatsapp': 'WhatsApp',
    'contact.email': 'Email',
    'contact.formTitle': 'Contact Us',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Your name',
    'contact.phonePlaceholder': 'Your phone',
    'contact.emailPlaceholder': 'your@email.com',
    'contact.service': 'Product of interest',
    'contact.servicePlaceholder': 'Ex: AJOLOTIUS® Syrup',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us about your inquiry...',
    'contact.send': 'Send Message',
    'contact.sending': 'Sending...',
    'contact.sent': 'Message sent!',
    'contact.sentDesc': 'We will get in touch with you soon.',
    
    // Footer
    'footer.description': 'Productos Camacho. Tradition, quality and natural wellness since 1985.',
    'footer.services': 'Products',
    'footer.generalDentistry': 'Natural Oils',
    'footer.whitening': 'Medicinal Ointments',
    'footer.implants': 'Cough Syrups',
    'footer.orthodontics': 'Lotions',
    'footer.aesthetics': 'Pharmacy Products',
    'footer.specialties': 'Categories',
    'footer.endodontics': 'Chemicals',
    'footer.periodontics': 'Botanicals',
    'footer.oralSurgery': 'Balms',
    'footer.pediatric': 'Medicinal Wines',
    'footer.prosthetics': 'Glycerins',
    'footer.contact': 'Contact',
    'footer.rights': 'All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms and Conditions',
    
    // Auth
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.fullName': 'Full name',
    'auth.phone': 'Phone',
    'auth.continue': 'Continue',
    'auth.createAccount': 'Create account',
    'auth.welcome': 'Welcome',
    'auth.accessPortal': 'Access your account',
    'auth.joinUs': 'Join Productos Camacho',
    'auth.patient': 'Customer',
    'auth.doctor': 'Distributor',
    'auth.experience': 'Quality natural products',
    
    // ChatBot
    'chatbot.title': 'Camacho',
    'chatbot.subtitle': 'Your health assistant 🌿',
    'chatbot.greeting': 'Hello! 👋',
    'chatbot.greetingText': 'I\'m your virtual assistant. How can I help you?',
    'chatbot.placeholder': 'Write your message...',
    'chatbot.typing': 'Typing...',
    'chatbot.services': 'Products',
    'chatbot.branches': 'Location',
    'chatbot.appointment': 'Order',
    'chatbot.prices': 'Prices',
    'chatbot.servicesQ': 'What products do you have?',
    'chatbot.branchesQ': 'Where can I buy your products?',
    'chatbot.appointmentQ': 'How can I place an order?',
    'chatbot.pricesQ': 'What are your wholesale prices?',
    
    // Dashboard Common
    'dashboard.appointments': 'Orders',
    'dashboard.calendar': 'Calendar',
    'dashboard.doctors': 'Distributors',
    'dashboard.analytics': 'Analytics',
    'dashboard.metrics': 'Metrics',
    'dashboard.reviews': 'Reviews',
    'dashboard.files': 'Files',
    'dashboard.prescriptions': 'Invoices',
    'dashboard.documents': 'Documents',
    'dashboard.referrals': 'Referrals',
    'dashboard.logout': 'Logout',
    'dashboard.total': 'Total Orders',
    'dashboard.pending': 'Pending',
    'dashboard.confirmed': 'Confirmed',
    'dashboard.today': 'Today',
    'dashboard.tomorrow': 'Tomorrow',
    'dashboard.noAppointments': 'No orders',
    'dashboard.noAppointmentsFiltered': 'No orders found with selected filters.',
    'dashboard.noAppointmentsYet': 'No orders yet.',
    'dashboard.loading': 'Loading orders...',
    'dashboard.searchPlaceholder': 'Search by name, email or phone...',
    'dashboard.all': 'All',
    'dashboard.allLocations': 'All',
    'dashboard.status': 'Status',
    'dashboard.branch': 'Warehouse',
    
    // Admin Dashboard
    'admin.title': 'Admin Panel',
    'admin.completed': 'Completed',
    'admin.cancelled': 'Cancelled',
    
    // Common
    'common.loading': 'Loading...',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.print': 'Print',
  },
  pt: {
    // Navigation
    'nav.home': 'Início',
    'nav.about': 'Sobre Nós',
    'nav.specialties': 'Categorias',
    'nav.services': 'Produtos',
    'nav.appointments': 'Loja',
    'nav.locations': 'Localizações',
    'nav.contact': 'Contato',
    'nav.login': 'Entrar',
    'nav.portal': 'Minha Conta',
    'nav.bookNow': 'Comprar Agora',
    
    // Hero
    'hero.badge': '✨ Tradição desde 1985',
    'hero.title1': 'Tradição, Qualidade e',
    'hero.title2': 'Bem-estar Natural',
    'hero.specialistsIn': 'Especialistas em',
    'hero.service1': 'Xaropes Naturais',
    'hero.service2': 'Pomadas Medicinais',
    'hero.service3': 'Óleos Essenciais',
    'hero.service4': 'Produtos de Farmácia',
    'hero.cta': 'Comprar Agora',
    'hero.secondary': 'Saiba Mais',
    'hero.years': 'Anos',
    'hero.branches': 'Categorias',
    'hero.specialties': 'Produtos',
    'hero.patients': 'Clientes',
    
    // About
    'about.badge': 'Sobre Nós',
    'about.title1': 'Tradição e Qualidade',
    'about.title2': 'Desde 1985',
    'about.description': 'Na <strong>Produtos Camacho</strong>, somos uma empresa 100% mexicana com mais de 40 anos de experiência na fabricação, embalagem e distribuição de <strong>xaropes para tosse</strong>, <strong>pomadas</strong>, <strong>óleos</strong> e produtos de <strong>farmácia tradicional</strong>.',
    'about.yearsExperience': 'Anos de tradição',
    'about.feature1.title': 'Ingredientes Naturais',
    'about.feature1.desc': 'Formulados com ingredientes naturais de eficácia comprovada.',
    'about.feature2.title': 'Qualidade Garantida',
    'about.feature2.desc': 'Processos de fabricação rigorosos que garantem qualidade.',
    'about.feature3.title': 'Tradição Mexicana',
    'about.feature3.desc': 'Preservamos as fórmulas magistrais da farmácia clássica.',
    'about.feature4.title': 'Distribuição Nacional',
    'about.feature4.desc': 'Chegamos a farmácias independentes e lojas naturais.',
    
    // Services/Products
    'services.badge': 'Nossos Produtos',
    'services.title': 'Qualidade que se sente',
    'services.subtitle': 'Produtos naturais com eficácia comprovada para o bem-estar da sua família.',
    'services.whitening': 'Xaropes',
    'services.whitening.desc': 'Xaropes naturais para tosse como AJOLOTIUS® e BRONCOPLUS®.',
    'services.whitening.f1': 'Ingredientes naturais',
    'services.whitening.f2': 'Eficácia comprovada',
    'services.implants': 'Pomadas',
    'services.implants.desc': 'Pomadas medicinais elaboradas com fórmulas tradicionais.',
    'services.implants.f1': 'Fórmulas tradicionais',
    'services.implants.f2': 'Múltiplos benefícios',
    'services.orthodontics': 'Óleos',
    'services.orthodontics.desc': 'Óleos essenciais e naturais da mais alta qualidade.',
    'services.orthodontics.f1': '100% Naturais',
    'services.orthodontics.f2': 'Alta pureza',
    'services.smileDesign': 'Produtos de Farmácia',
    'services.smileDesign.desc': 'Produtos tradicionais de farmácia como químicos e loções.',
    'services.smileDesign.f1': 'Receitas magistrais',
    'services.smileDesign.f2': 'Tradição mexicana',
    'services.schedule': 'Ver Produto',
    
    // Specialties/Categories
    'specialties.badge': 'Categorias',
    'specialties.title': 'Explore nosso catálogo',
    'specialties.subtitle': 'Mais de 165 produtos naturais para o cuidado da sua saúde.',
    'specialties.general': 'Óleos',
    'specialties.endodontics': 'Pomadas',
    'specialties.implantology': 'Xaropes',
    'specialties.maxillofacial': 'Loções',
    'specialties.orthodontics': 'Vinhos',
    'specialties.pediatric': 'Químicos',
    'specialties.prosthetics': 'Botânicos',
    'specialties.surgery': 'Bálsamos',
    'specialties.aesthetics': 'Glicerinas',
    
    // Footer
    'footer.description': 'Produtos Camacho. Tradição, qualidade e bem-estar natural desde 1985.',
    'footer.services': 'Produtos',
    'footer.generalDentistry': 'Óleos Naturais',
    'footer.whitening': 'Pomadas Medicinais',
    'footer.implants': 'Xaropes para Tosse',
    'footer.orthodontics': 'Loções',
    'footer.aesthetics': 'Produtos de Farmácia',
    'footer.specialties': 'Categorias',
    'footer.endodontics': 'Químicos',
    'footer.periodontics': 'Botânicos',
    'footer.oralSurgery': 'Bálsamos',
    'footer.pediatric': 'Vinhos Medicinais',
    'footer.prosthetics': 'Glicerinas',
    'footer.contact': 'Contato',
    'footer.rights': 'Todos os direitos reservados.',
    'footer.privacy': 'Política de Privacidade',
    'footer.terms': 'Termos e Condições',
    
    // Brands
    'brands.title': 'Nossas Marcas Registradas',
    'brands.subtitle': 'Marcas reconhecidas com ingredientes naturais e eficácia comprovada',
    'technology.title': 'Nossas Marcas',
    'technology.subtitle': 'Contamos com marcas registradas e reconhecidas como AJOLOTIUS® e BRONCOPLUS®',
    'technology.precision': 'AJOLOTIUS®',
    'technology.precisionDesc': 'Xarope natural para tosse com fórmula tradicional mexicana',
    'technology.speed': 'BRONCOPLUS®',
    'technology.speedDesc': 'Xarope bronquial com ingredientes naturais de eficácia comprovada',
    'technology.quality': 'Qualidade Premium',
    'technology.qualityDesc': 'Produtos aliados de farmácias independentes e distribuidores',
    
    // Common
    'common.loading': 'Carregando...',
    'common.save': 'Salvar',
    'common.cancel': 'Cancelar',
    'common.delete': 'Excluir',
    'common.edit': 'Editar',
    'common.view': 'Ver',
    'common.search': 'Buscar',
    'common.filter': 'Filtrar',
    'common.export': 'Exportar',
    'common.print': 'Imprimir',
    
    // Contact
    'contact.badge': 'Contato',
    'contact.title': 'Pronto para',
    'contact.titleHighlight': 'experimentar nossos produtos',
    'contact.subtitle': 'Estamos aqui para responder todas as suas perguntas.',
    'contact.callUs': 'Ligue para nós',
    'contact.whatsapp': 'WhatsApp',
    'contact.email': 'Email',
    'contact.formTitle': 'Entre em Contato',
    'contact.name': 'Nome',
    'contact.namePlaceholder': 'Seu nome',
    'contact.phonePlaceholder': 'Seu telefone',
    'contact.emailPlaceholder': 'seu@email.com',
    'contact.service': 'Produto de interesse',
    'contact.servicePlaceholder': 'Ex: Xarope AJOLOTIUS®',
    'contact.message': 'Mensagem',
    'contact.messagePlaceholder': 'Conte-nos sobre sua consulta...',
    'contact.send': 'Enviar Mensagem',
    'contact.sending': 'Enviando...',
    'contact.sent': 'Mensagem enviada!',
    'contact.sentDesc': 'Entraremos em contato em breve.',
    
    // CTA
    'cta.title': 'Seu bem-estar nos importa',
    'cta.subtitle': 'Descubra nossa linha completa de produtos naturais.',
    'cta.button': 'Ver Catálogo',
    'cta.call': 'Ligar Agora',
    
    // Locations
    'locations.badge': 'Onde nos encontrar?',
    'locations.title': 'Encontre',
    'locations.titleHighlight': 'nossos produtos',
    'locations.subtitle': 'Nossos produtos estão disponíveis em farmácias independentes e lojas naturais.',
    'locations.viewMap': 'Ver mapa',
    'locations.hours': 'Seg - Sex: 9:00 - 18:00',
    'locations.directions': 'Como chegar',
    
    // Testimonials
    'testimonials.badge': 'Depoimentos',
    'testimonials.title': 'O que dizem',
    'testimonials.titleHighlight': 'nossos clientes',
    'testimonials.subtitle': 'Histórias reais de clientes que confiam em nossos produtos.',
    'testimonials.patientSince': 'Cliente desde',
    
    // Reviews
    'reviews.badge': 'Avaliações de Clientes',
    'reviews.title': 'O que dizem',
    'reviews.titleHighlight': 'nossos clientes',
    'reviews.reviews': 'avaliações',
  },
  ru: {
    // Navigation
    'nav.home': 'Главная',
    'nav.about': 'О нас',
    'nav.specialties': 'Категории',
    'nav.services': 'Продукты',
    'nav.appointments': 'Магазин',
    'nav.locations': 'Локации',
    'nav.contact': 'Контакты',
    'nav.login': 'Войти',
    'nav.portal': 'Мой кабинет',
    'nav.bookNow': 'Купить сейчас',
    
    // Hero
    'hero.badge': '✨ Традиция с 1985',
    'hero.title1': 'Традиция, Качество и',
    'hero.title2': 'Натуральное Здоровье',
    'hero.specialistsIn': 'Специалисты в',
    'hero.service1': 'Натуральные сиропы',
    'hero.service2': 'Лечебные мази',
    'hero.service3': 'Эфирные масла',
    'hero.service4': 'Аптечные продукты',
    'hero.cta': 'Купить сейчас',
    'hero.secondary': 'Узнать больше',
    'hero.years': 'Лет',
    'hero.branches': 'Категории',
    'hero.specialties': 'Продукты',
    'hero.patients': 'Клиенты',
    
    // About
    'about.badge': 'О нас',
    'about.title1': 'Традиция и Качество',
    'about.title2': 'С 1985 года',
    'about.description': 'В <strong>Productos Camacho</strong> мы являемся 100% мексиканской компанией с более чем 40-летним опытом в производстве и распространении <strong>сиропов от кашля</strong>, <strong>мазей</strong>, <strong>масел</strong> и <strong>традиционных аптечных продуктов</strong>.',
    'about.yearsExperience': 'Лет традиции',
    'about.feature1.title': 'Натуральные ингредиенты',
    'about.feature1.desc': 'Формулы с натуральными ингредиентами проверенной эффективности.',
    'about.feature2.title': 'Гарантия качества',
    'about.feature2.desc': 'Строгие процессы производства гарантируют качество.',
    'about.feature3.title': 'Мексиканская традиция',
    'about.feature3.desc': 'Мы сохраняем мастерские формулы классической аптеки.',
    'about.feature4.title': 'Национальная дистрибуция',
    'about.feature4.desc': 'Мы достигаем независимых аптек и натуральных магазинов.',
    
    // Services/Products
    'services.badge': 'Наши продукты',
    'services.title': 'Качество, которое чувствуется',
    'services.subtitle': 'Натуральные продукты с доказанной эффективностью для здоровья вашей семьи.',
    'services.whitening': 'Сиропы',
    'services.whitening.desc': 'Натуральные сиропы от кашля AJOLOTIUS® и BRONCOPLUS®.',
    'services.whitening.f1': 'Натуральные ингредиенты',
    'services.whitening.f2': 'Доказанная эффективность',
    'services.implants': 'Мази',
    'services.implants.desc': 'Лечебные мази с традиционными формулами.',
    'services.implants.f1': 'Традиционные формулы',
    'services.implants.f2': 'Множество преимуществ',
    'services.orthodontics': 'Масла',
    'services.orthodontics.desc': 'Эфирные и натуральные масла высочайшего качества.',
    'services.orthodontics.f1': '100% Натуральные',
    'services.orthodontics.f2': 'Высокая чистота',
    'services.smileDesign': 'Аптечные продукты',
    'services.smileDesign.desc': 'Традиционные аптечные продукты как химикаты и лосьоны.',
    'services.smileDesign.f1': 'Мастерские рецепты',
    'services.smileDesign.f2': 'Мексиканская традиция',
    'services.schedule': 'Посмотреть',
    
    // Specialties/Categories
    'specialties.badge': 'Категории',
    'specialties.title': 'Исследуйте наш каталог',
    'specialties.subtitle': 'Более 165 натуральных продуктов для вашего здоровья.',
    'specialties.general': 'Масла',
    'specialties.endodontics': 'Мази',
    'specialties.implantology': 'Сиропы',
    'specialties.maxillofacial': 'Лосьоны',
    'specialties.orthodontics': 'Вина',
    'specialties.pediatric': 'Химикаты',
    'specialties.prosthetics': 'Ботаника',
    'specialties.surgery': 'Бальзамы',
    'specialties.aesthetics': 'Глицерины',
    
    // Footer
    'footer.description': 'Productos Camacho. Традиция, качество и натуральное здоровье с 1985.',
    'footer.services': 'Продукты',
    'footer.generalDentistry': 'Натуральные масла',
    'footer.whitening': 'Лечебные мази',
    'footer.implants': 'Сиропы от кашля',
    'footer.orthodontics': 'Лосьоны',
    'footer.aesthetics': 'Аптечные продукты',
    'footer.specialties': 'Категории',
    'footer.endodontics': 'Химикаты',
    'footer.periodontics': 'Ботаника',
    'footer.oralSurgery': 'Бальзамы',
    'footer.pediatric': 'Лечебные вина',
    'footer.prosthetics': 'Глицерины',
    'footer.contact': 'Контакты',
    'footer.rights': 'Все права защищены.',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия использования',
    
    // Brands
    'brands.title': 'Наши Торговые Марки',
    'brands.subtitle': 'Признанные бренды с натуральными ингредиентами',
    'technology.title': 'Наши Бренды',
    'technology.subtitle': 'У нас есть зарегистрированные торговые марки AJOLOTIUS® и BRONCOPLUS®',
    'technology.precision': 'AJOLOTIUS®',
    'technology.precisionDesc': 'Натуральный сироп от кашля с традиционной мексиканской формулой',
    'technology.speed': 'BRONCOPLUS®',
    'technology.speedDesc': 'Бронхиальный сироп с натуральными ингредиентами',
    'technology.quality': 'Премиум Качество',
    'technology.qualityDesc': 'Продукты для независимых аптек и дистрибьюторов',
    
    // Common
    'common.loading': 'Загрузка...',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.view': 'Просмотр',
    'common.search': 'Поиск',
    'common.filter': 'Фильтр',
    'common.export': 'Экспорт',
    'common.print': 'Печать',
    
    // Contact
    'contact.badge': 'Контакты',
    'contact.title': 'Готовы',
    'contact.titleHighlight': 'попробовать наши продукты',
    'contact.subtitle': 'Мы здесь, чтобы ответить на все ваши вопросы.',
    'contact.callUs': 'Позвоните нам',
    'contact.whatsapp': 'WhatsApp',
    'contact.email': 'Email',
    'contact.formTitle': 'Свяжитесь с нами',
    'contact.name': 'Имя',
    'contact.namePlaceholder': 'Ваше имя',
    'contact.phonePlaceholder': 'Ваш телефон',
    'contact.emailPlaceholder': 'ваш@email.com',
    'contact.service': 'Интересующий продукт',
    'contact.servicePlaceholder': 'Пример: Сироп AJOLOTIUS®',
    'contact.message': 'Сообщение',
    'contact.messagePlaceholder': 'Расскажите нам о вашем запросе...',
    'contact.send': 'Отправить',
    'contact.sending': 'Отправка...',
    'contact.sent': 'Сообщение отправлено!',
    'contact.sentDesc': 'Мы свяжемся с вами в ближайшее время.',
    
    // CTA
    'cta.title': 'Ваше здоровье важно для нас',
    'cta.subtitle': 'Откройте нашу полную линейку натуральных продуктов.',
    'cta.button': 'Посмотреть каталог',
    'cta.call': 'Позвонить',
    
    // Locations
    'locations.badge': 'Где нас найти?',
    'locations.title': 'Найдите',
    'locations.titleHighlight': 'наши продукты',
    'locations.subtitle': 'Наши продукты доступны в независимых аптеках и натуральных магазинах.',
    'locations.viewMap': 'Посмотреть карту',
    'locations.hours': 'Пн - Пт: 9:00 - 18:00',
    'locations.directions': 'Как добраться',
    
    // Testimonials
    'testimonials.badge': 'Отзывы',
    'testimonials.title': 'Что говорят',
    'testimonials.titleHighlight': 'наши клиенты',
    'testimonials.subtitle': 'Реальные истории клиентов, которые доверяют нашим продуктам.',
    'testimonials.patientSince': 'Клиент с',
    
    // Reviews
    'reviews.badge': 'Отзывы клиентов',
    'reviews.title': 'Что говорят',
    'reviews.titleHighlight': 'наши клиенты',
    'reviews.reviews': 'отзывов',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const stored = localStorage.getItem('language') as Language;
    return stored || 'es';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations['es'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
