-- Insert professional marketing templates for dental clinic features
INSERT INTO public.email_templates (name, description, blocks, global_styles, category, is_default) VALUES
(
  'Tu Clínica con IA',
  'Plantilla promocional de las funcionalidades de inteligencia artificial',
  '[
    {"id":"logo-1","type":"logo","content":{"text":"NovellDent","emoji":"🦷"},"styles":{"alignment":"center","fontSize":28,"color":"#1e3a5f"}},
    {"id":"spacer-1","type":"spacer","content":{},"styles":{"height":20}},
    {"id":"heading-1","type":"heading","content":{"text":"🤖 Tu Clínica con Inteligencia Artificial"},"styles":{"fontSize":28,"fontWeight":"bold","color":"#7c3aed","alignment":"center"}},
    {"id":"spacer-2","type":"spacer","content":{},"styles":{"height":12}},
    {"id":"text-1","type":"text","content":{"text":"Descubre cómo la IA puede transformar la operación de tu clínica dental. Ahorra tiempo, mejora diagnósticos y ofrece una experiencia excepcional a tus pacientes."},"styles":{"fontSize":15,"color":"#4b5563","alignment":"center","lineHeight":1.7}},
    {"id":"spacer-3","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"list-1","type":"list","content":{"items":["🔬 Análisis de RX - Ahorra tiempo en cada diagnóstico con análisis automático","📊 Reportes IA - Consulta ingresos, citas, tratamientos al instante","📞 Contact Center - Atiende llamadas y WhatsApp automáticamente","📋 Resumen Clínico - Datos relevantes antes de cada consulta","🎯 Contralor IA - Supervisa flujos clínicos y administrativos","😁 Simulador de Sonrisas - Proyecciones realistas con IA"]},"styles":{"fontSize":14,"color":"#374151","bulletColor":"#7c3aed"}},
    {"id":"spacer-4","type":"spacer","content":{},"styles":{"height":28}},
    {"id":"button-1","type":"button","content":{"text":"Conocer más sobre IA","url":"#"},"styles":{"backgroundColor":"#7c3aed","color":"#ffffff","fontSize":16,"padding":16,"borderRadius":8,"alignment":"center"}},
    {"id":"spacer-5","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"social-1","type":"social","content":{"facebook":"https://facebook.com","instagram":"https://instagram.com","twitter":"","linkedin":"","youtube":"","website":"https://novelldent.com"},"styles":{"alignment":"center","iconSize":22,"iconColor":"#7c3aed","spacing":14}},
    {"id":"footer-1","type":"footer","content":{"companyName":"NovellDent","address":"Av. Principal 123, Ciudad","phone":"+1 234 567 890","email":"info@novelldent.com","links":[{"text":"Demo gratis","url":"#"},{"text":"Contacto","url":"#"}],"unsubscribeText":"Si no deseas recibir estos mensajes, puedes darte de baja aquí"},"styles":{"backgroundColor":"#7c3aed","textColor":"#ffffff","fontSize":12,"padding":24}}
  ]'::jsonb,
  '{"backgroundColor":"#f5f3ff","contentBackground":"#ffffff","fontFamily":"Arial, sans-serif","primaryColor":"#7c3aed","secondaryColor":"#1e3a5f","textColor":"#374151","width":600}'::jsonb,
  'promotion',
  true
),
(
  'Conecta con más Pacientes',
  'Plantilla para promocionar herramientas de comunicación y captación',
  '[
    {"id":"logo-1","type":"logo","content":{"text":"NovellDent","emoji":"🦷"},"styles":{"alignment":"center","fontSize":26,"color":"#1e3a5f"}},
    {"id":"spacer-1","type":"spacer","content":{},"styles":{"height":20}},
    {"id":"heading-1","type":"heading","content":{"text":"📱 Conecta con más Pacientes"},"styles":{"fontSize":26,"fontWeight":"bold","color":"#0891b2","alignment":"center"}},
    {"id":"spacer-2","type":"spacer","content":{},"styles":{"height":16}},
    {"id":"text-1","type":"text","content":{"text":"Nunca pierdas una oportunidad. Atiende a tus pacientes por múltiples canales y automatiza la comunicación para una experiencia excepcional."},"styles":{"fontSize":15,"color":"#4b5563","alignment":"center","lineHeight":1.6}},
    {"id":"spacer-3","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"columns-1","type":"columns","content":{"left":"📞 Contact Center IA\n\nAtiende llamadas, responde WhatsApp y agenda citas automáticamente sin perder ningún paciente.","right":"💬 Chat Interno\n\nMejora la comunicación de tu equipo con mensajería instantánea integrada."},"styles":{"gap":24,"fontSize":14,"color":"#374151"}},
    {"id":"spacer-4","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"divider-1","type":"divider","content":{},"styles":{"color":"#0891b2","thickness":2,"width":30,"style":"solid"}},
    {"id":"spacer-5","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"text-2","type":"text","content":{"text":"\"Desde que implementamos el Contact Center, nuestra tasa de respuesta aumentó un 85%\""},"styles":{"fontSize":14,"color":"#0891b2","alignment":"center","lineHeight":1.6}},
    {"id":"spacer-6","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"button-1","type":"button","content":{"text":"Solicitar demostración","url":"#"},"styles":{"backgroundColor":"#0891b2","color":"#ffffff","fontSize":15,"padding":16,"borderRadius":8,"alignment":"center"}},
    {"id":"footer-1","type":"footer","content":{"companyName":"NovellDent","address":"Av. Principal 123, Ciudad","phone":"+1 234 567 890","email":"info@novelldent.com","links":[{"text":"Funcionalidades","url":"#"},{"text":"Precios","url":"#"}],"unsubscribeText":"Gestiona tus preferencias de email aquí"},"styles":{"backgroundColor":"#0891b2","textColor":"#ffffff","fontSize":12,"padding":24}}
  ]'::jsonb,
  '{"backgroundColor":"#ecfeff","contentBackground":"#ffffff","fontFamily":"Arial, sans-serif","primaryColor":"#0891b2","secondaryColor":"#1e3a5f","textColor":"#374151","width":600}'::jsonb,
  'promotion',
  true
),
(
  'Mejora tu Atención Clínica',
  'Plantilla destacando herramientas clínicas avanzadas',
  '[
    {"id":"logo-1","type":"logo","content":{"text":"NovellDent","emoji":"🦷"},"styles":{"alignment":"center","fontSize":26,"color":"#1e3a5f"}},
    {"id":"spacer-1","type":"spacer","content":{},"styles":{"height":20}},
    {"id":"heading-1","type":"heading","content":{"text":"🩺 Mejora tu Atención Clínica"},"styles":{"fontSize":26,"fontWeight":"bold","color":"#059669","alignment":"center"}},
    {"id":"spacer-2","type":"spacer","content":{},"styles":{"height":16}},
    {"id":"text-1","type":"text","content":{"text":"Herramientas diseñadas para optimizar cada consulta y brindar el mejor cuidado a tus pacientes."},"styles":{"fontSize":15,"color":"#4b5563","alignment":"center","lineHeight":1.6}},
    {"id":"spacer-3","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"list-1","type":"list","content":{"items":["🎙️ Notas Clínicas - Transforma tu voz en evoluciones estructuradas","📁 Historia Clínica - Toda la información en un solo lugar","🦷 Odontograma - Registra lesiones y progresos en tiempo real","🔧 Módulo de Ortodoncia - Control integral de tratamientos","✍️ Consentimientos Digitales - Firma electrónica de documentos","📸 Carga de Imágenes - Almacena documentos clínicos fácilmente"]},"styles":{"fontSize":14,"color":"#374151","bulletColor":"#059669"}},
    {"id":"spacer-4","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"heading-2","type":"heading","content":{"text":"✨ NUEVO: Estética Facial"},"styles":{"fontSize":18,"fontWeight":"bold","color":"#059669","alignment":"center"}},
    {"id":"text-2","type":"text","content":{"text":"Crea presupuestos acompañados de un esquema facial completo para tratamientos estéticos."},"styles":{"fontSize":14,"color":"#6b7280","alignment":"center","lineHeight":1.5}},
    {"id":"spacer-5","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"button-1","type":"button","content":{"text":"Ver todas las funciones clínicas","url":"#"},"styles":{"backgroundColor":"#059669","color":"#ffffff","fontSize":15,"padding":16,"borderRadius":8,"alignment":"center"}},
    {"id":"footer-1","type":"footer","content":{"companyName":"NovellDent","address":"Av. Principal 123, Ciudad","phone":"+1 234 567 890","email":"info@novelldent.com","links":[{"text":"Casos de éxito","url":"#"},{"text":"Soporte","url":"#"}],"unsubscribeText":"Gestiona tus preferencias de email aquí"},"styles":{"backgroundColor":"#059669","textColor":"#ffffff","fontSize":12,"padding":24}}
  ]'::jsonb,
  '{"backgroundColor":"#ecfdf5","contentBackground":"#ffffff","fontFamily":"Arial, sans-serif","primaryColor":"#059669","secondaryColor":"#1e3a5f","textColor":"#374151","width":600}'::jsonb,
  'promotion',
  true
),
(
  'Controla tu Operación',
  'Plantilla para promocionar herramientas administrativas y de control',
  '[
    {"id":"logo-1","type":"logo","content":{"text":"NovellDent","emoji":"🦷"},"styles":{"alignment":"center","fontSize":26,"color":"#1e3a5f"}},
    {"id":"spacer-1","type":"spacer","content":{},"styles":{"height":20}},
    {"id":"heading-1","type":"heading","content":{"text":"📊 Controla tu Operación"},"styles":{"fontSize":26,"fontWeight":"bold","color":"#ea580c","alignment":"center"}},
    {"id":"spacer-2","type":"spacer","content":{},"styles":{"height":16}},
    {"id":"text-1","type":"text","content":{"text":"Gestiona todos los aspectos administrativos de tu clínica desde una sola plataforma. Mayor control, mejores resultados."},"styles":{"fontSize":15,"color":"#4b5563","alignment":"center","lineHeight":1.6}},
    {"id":"spacer-3","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"columns-1","type":"columns","content":{"left":"💰 Finanzas\n• Control de caja\n• Control de gastos\n• Pago a odontólogos","right":"📦 Operaciones\n• Gestión de laboratorios\n• Control de inventario\n• Carga masiva de pacientes"},"styles":{"gap":24,"fontSize":14,"color":"#374151"}},
    {"id":"spacer-4","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"divider-1","type":"divider","content":{},"styles":{"color":"#ea580c","thickness":2,"width":40,"style":"solid"}},
    {"id":"spacer-5","type":"spacer","content":{},"styles":{"height":20}},
    {"id":"heading-2","type":"heading","content":{"text":"📈 Reportes y Análisis"},"styles":{"fontSize":18,"fontWeight":"bold","color":"#ea580c","alignment":"center"}},
    {"id":"text-2","type":"text","content":{"text":"Más de 50 reportes descargables + KPIs gráficos para analizar tu clínica al detalle. Toma decisiones basadas en datos reales."},"styles":{"fontSize":14,"color":"#6b7280","alignment":"center","lineHeight":1.6}},
    {"id":"spacer-6","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"button-1","type":"button","content":{"text":"Optimiza tu gestión ahora","url":"#"},"styles":{"backgroundColor":"#ea580c","color":"#ffffff","fontSize":15,"padding":16,"borderRadius":8,"alignment":"center"}},
    {"id":"footer-1","type":"footer","content":{"companyName":"NovellDent","address":"Av. Principal 123, Ciudad","phone":"+1 234 567 890","email":"info@novelldent.com","links":[{"text":"Planes","url":"#"},{"text":"Contacto","url":"#"}],"unsubscribeText":"Gestiona tus preferencias de email aquí"},"styles":{"backgroundColor":"#ea580c","textColor":"#ffffff","fontSize":12,"padding":24}}
  ]'::jsonb,
  '{"backgroundColor":"#fff7ed","contentBackground":"#ffffff","fontFamily":"Arial, sans-serif","primaryColor":"#ea580c","secondaryColor":"#1e3a5f","textColor":"#374151","width":600}'::jsonb,
  'promotion',
  true
),
(
  'Fideliza tus Pacientes',
  'Plantilla para programas de fidelización y retención',
  '[
    {"id":"logo-1","type":"logo","content":{"text":"NovellDent","emoji":"🦷"},"styles":{"alignment":"center","fontSize":26,"color":"#1e3a5f"}},
    {"id":"spacer-1","type":"spacer","content":{},"styles":{"height":20}},
    {"id":"heading-1","type":"heading","content":{"text":"❤️ Fideliza y haz que Regresen"},"styles":{"fontSize":26,"fontWeight":"bold","color":"#db2777","alignment":"center"}},
    {"id":"spacer-2","type":"spacer","content":{},"styles":{"height":16}},
    {"id":"text-1","type":"text","content":{"text":"Construye relaciones duraderas con tus pacientes. Herramientas diseñadas para mantenerlos comprometidos y satisfechos."},"styles":{"fontSize":15,"color":"#4b5563","alignment":"center","lineHeight":1.6}},
    {"id":"spacer-3","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"list-1","type":"list","content":{"items":["📅 Control de Agenda - Evita demoras y optimiza tiempos","🎥 Videos 3D - Enseña los procedimientos a tus pacientes","📝 Plantillas Personalizables - Recetas y prescripciones profesionales","📄 Documentos Clínicos - Gestiona con agilidad","🔔 Recordatorios Automáticos - Nunca olvidan sus citas","🎁 Programa de Referidos - Incentiva las recomendaciones"]},"styles":{"fontSize":14,"color":"#374151","bulletColor":"#db2777"}},
    {"id":"spacer-4","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"text-2","type":"text","content":{"text":"\"Los pacientes que entienden su tratamiento tienen 3x más probabilidad de completarlo\""},"styles":{"fontSize":14,"color":"#db2777","alignment":"center","lineHeight":1.6}},
    {"id":"spacer-5","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"button-1","type":"button","content":{"text":"Aumenta tu retención de pacientes","url":"#"},"styles":{"backgroundColor":"#db2777","color":"#ffffff","fontSize":15,"padding":16,"borderRadius":24,"alignment":"center"}},
    {"id":"social-1","type":"social","content":{"facebook":"https://facebook.com","instagram":"https://instagram.com","twitter":"","linkedin":"","youtube":"","website":""},"styles":{"alignment":"center","iconSize":22,"iconColor":"#db2777","spacing":14}},
    {"id":"footer-1","type":"footer","content":{"companyName":"NovellDent","address":"Av. Principal 123, Ciudad","phone":"+1 234 567 890","email":"info@novelldent.com","links":[{"text":"Testimonios","url":"#"},{"text":"Blog","url":"#"}],"unsubscribeText":"Gestiona tus preferencias de email aquí"},"styles":{"backgroundColor":"#db2777","textColor":"#ffffff","fontSize":12,"padding":24}}
  ]'::jsonb,
  '{"backgroundColor":"#fdf2f8","contentBackground":"#ffffff","fontFamily":"Arial, sans-serif","primaryColor":"#db2777","secondaryColor":"#1e3a5f","textColor":"#374151","width":600}'::jsonb,
  'loyalty',
  true
),
(
  'Aumenta tus Ingresos',
  'Plantilla enfocada en crecimiento y rentabilidad',
  '[
    {"id":"logo-1","type":"logo","content":{"text":"NovellDent","emoji":"🦷"},"styles":{"alignment":"center","fontSize":26,"color":"#1e3a5f"}},
    {"id":"spacer-1","type":"spacer","content":{},"styles":{"height":20}},
    {"id":"heading-1","type":"heading","content":{"text":"💰 Aumenta tus Ingresos"},"styles":{"fontSize":28,"fontWeight":"bold","color":"#16a34a","alignment":"center"}},
    {"id":"spacer-2","type":"spacer","content":{},"styles":{"height":16}},
    {"id":"text-1","type":"text","content":{"text":"Maximiza la rentabilidad de tu clínica con herramientas que optimizan cada aspecto de tu operación."},"styles":{"fontSize":15,"color":"#4b5563","alignment":"center","lineHeight":1.6}},
    {"id":"spacer-3","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"heading-2","type":"heading","content":{"text":"Clínicas que usan NovellDent reportan:"},"styles":{"fontSize":16,"fontWeight":"bold","color":"#374151","alignment":"center"}},
    {"id":"spacer-4","type":"spacer","content":{},"styles":{"height":16}},
    {"id":"columns-1","type":"columns","content":{"left":"📈 +35%\nIngresos promedio\n\n⏱️ -40%\nTiempo administrativo","right":"👥 +50%\nRetención de pacientes\n\n📅 -60%\nCitas no asistidas"},"styles":{"gap":24,"fontSize":15,"color":"#16a34a"}},
    {"id":"spacer-5","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"divider-1","type":"divider","content":{},"styles":{"color":"#16a34a","thickness":2,"width":40,"style":"solid"}},
    {"id":"spacer-6","type":"spacer","content":{},"styles":{"height":20}},
    {"id":"list-1","type":"list","content":{"items":["Control de caja y gastos en tiempo real","Cálculo automático de pagos a odontólogos","Reportes KPI para decisiones estratégicas","Gestión eficiente de inventario"]},"styles":{"fontSize":14,"color":"#374151","bulletColor":"#16a34a"}},
    {"id":"spacer-7","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"button-1","type":"button","content":{"text":"Calcula tu ROI gratis","url":"#"},"styles":{"backgroundColor":"#16a34a","color":"#ffffff","fontSize":16,"padding":18,"borderRadius":8,"alignment":"center"}},
    {"id":"footer-1","type":"footer","content":{"companyName":"NovellDent","address":"Av. Principal 123, Ciudad","phone":"+1 234 567 890","email":"info@novelldent.com","links":[{"text":"Casos de éxito","url":"#"},{"text":"Precios","url":"#"}],"unsubscribeText":"Gestiona tus preferencias de email aquí"},"styles":{"backgroundColor":"#16a34a","textColor":"#ffffff","fontSize":12,"padding":24}}
  ]'::jsonb,
  '{"backgroundColor":"#f0fdf4","contentBackground":"#ffffff","fontFamily":"Arial, sans-serif","primaryColor":"#16a34a","secondaryColor":"#1e3a5f","textColor":"#374151","width":600}'::jsonb,
  'promotion',
  true
),
(
  'Newsletter Mensual',
  'Plantilla para boletín informativo mensual con novedades',
  '[
    {"id":"logo-1","type":"logo","content":{"text":"NovellDent","emoji":"🦷"},"styles":{"alignment":"center","fontSize":26,"color":"#1e3a5f"}},
    {"id":"spacer-1","type":"spacer","content":{},"styles":{"height":16}},
    {"id":"text-1","type":"text","content":{"text":"BOLETÍN MENSUAL • ENERO 2026"},"styles":{"fontSize":12,"color":"#6b7280","alignment":"center","lineHeight":1.5}},
    {"id":"spacer-2","type":"spacer","content":{},"styles":{"height":16}},
    {"id":"heading-1","type":"heading","content":{"text":"📰 Novedades de NovellDent"},"styles":{"fontSize":24,"fontWeight":"bold","color":"#1e3a5f","alignment":"center"}},
    {"id":"spacer-3","type":"spacer","content":{},"styles":{"height":20}},
    {"id":"divider-1","type":"divider","content":{},"styles":{"color":"#e5e7eb","thickness":1,"width":80,"style":"solid"}},
    {"id":"spacer-4","type":"spacer","content":{},"styles":{"height":20}},
    {"id":"heading-2","type":"heading","content":{"text":"🎉 Nueva función: Estética Facial"},"styles":{"fontSize":18,"fontWeight":"bold","color":"#3b82f6","alignment":"left"}},
    {"id":"text-2","type":"text","content":{"text":"Ahora puedes crear presupuestos acompañados de un esquema facial completo. Ideal para tratamientos de estética dental y facial."},"styles":{"fontSize":14,"color":"#4b5563","alignment":"left","lineHeight":1.6}},
    {"id":"spacer-5","type":"spacer","content":{},"styles":{"height":20}},
    {"id":"heading-3","type":"heading","content":{"text":"💡 Tip del mes"},"styles":{"fontSize":18,"fontWeight":"bold","color":"#3b82f6","alignment":"left"}},
    {"id":"text-3","type":"text","content":{"text":"¿Sabías que puedes usar comandos de voz para crear notas clínicas? Activa el micrófono y dicta tus evoluciones para ahorrar hasta 15 minutos por paciente."},"styles":{"fontSize":14,"color":"#4b5563","alignment":"left","lineHeight":1.6}},
    {"id":"spacer-6","type":"spacer","content":{},"styles":{"height":20}},
    {"id":"heading-4","type":"heading","content":{"text":"📅 Próximos webinars"},"styles":{"fontSize":18,"fontWeight":"bold","color":"#3b82f6","alignment":"left"}},
    {"id":"list-1","type":"list","content":{"items":["15 Ene - Optimiza tu agenda con IA","22 Ene - Reportes KPI para tu clínica","29 Ene - Fidelización de pacientes"]},"styles":{"fontSize":14,"color":"#374151","bulletColor":"#3b82f6"}},
    {"id":"spacer-7","type":"spacer","content":{},"styles":{"height":24}},
    {"id":"button-1","type":"button","content":{"text":"Ver todos los recursos","url":"#"},"styles":{"backgroundColor":"#3b82f6","color":"#ffffff","fontSize":14,"padding":14,"borderRadius":8,"alignment":"center"}},
    {"id":"social-1","type":"social","content":{"facebook":"https://facebook.com","instagram":"https://instagram.com","twitter":"","linkedin":"https://linkedin.com","youtube":"https://youtube.com","website":""},"styles":{"alignment":"center","iconSize":22,"iconColor":"#3b82f6","spacing":14}},
    {"id":"footer-1","type":"footer","content":{"companyName":"NovellDent","address":"Av. Principal 123, Ciudad","phone":"+1 234 567 890","email":"info@novelldent.com","links":[{"text":"Blog","url":"#"},{"text":"Ayuda","url":"#"},{"text":"Contacto","url":"#"}],"unsubscribeText":"Gestiona tus preferencias de email o date de baja aquí"},"styles":{"backgroundColor":"#1e3a5f","textColor":"#ffffff","fontSize":12,"padding":24}}
  ]'::jsonb,
  '{"backgroundColor":"#f8fafc","contentBackground":"#ffffff","fontFamily":"Arial, sans-serif","primaryColor":"#3b82f6","secondaryColor":"#1e3a5f","textColor":"#374151","width":600}'::jsonb,
  'newsletter',
  true
);