// Re-export all clinical section components
export { PatientHistorySection } from './PatientHistorySection';
export { PatientEvolutionsSection } from './PatientEvolutionsSection';
export { PatientMedicalHistorySection } from './PatientMedicalHistorySection';
export { PatientOdontogramSection } from './PatientOdontogramSection';
export { PatientPeriodontogramSection } from './PatientPeriodontogramSection';
export { PatientImagingSection } from './PatientImagingSection';
export { PatientPrescriptionsSection } from './PatientPrescriptionsSection';
export { PatientDocumentsSection } from './PatientDocumentsSection';
export { PatientConsentsSection } from './PatientConsentsSection';
